http://bit.ly/2x0kWxC

# Variables
We use variables to temporarily store data in computer’s memory. 

In [ ]:
pip uninstall opencv-python
pip install opencv-python==3.4.3.18
pip install opencv-contrib-python
pip install cmake
pip install dlib

In [13]:
price = "20"
type(price)

str

#### The equal sign (=) is used to assign a value to a variable. Afterwards, no result is displayed before the next interactive prompt:

In [3]:
 width = 20
print(width)
print(type(width))

20
<class 'int'>


In [69]:
x=10
#0b is the prefix to evoke binary numbers 
x=0b10
#bin stands for binary representation
print(bin(x))
x=0x12c
print(hex(x))
#complex number
x=1+2j
print(x)

0b10
0x12c
(1+2j)


In [71]:
print(bool(0))

False


In [3]:
print(bool(1))
print(bool(0))
print(bool(""))
print(bool("True"))
print(bool([]))
print(bool(None))

True
False
False
True
False
False


In [4]:
rating = 4.9 
type(rating)

float

### Ternary Operator

In [80]:
age=22
# message=age >=18 ? "Eligible" : "Not Eligible"
message="Eligible" if age>=18 else "Not eligible"
print(message)

Eligible


In [11]:
course_name = "Python for Beginners" 
print(id(course_name))
print(id(course_name[0]))
print(course_name)
print(type(course_name))

2866034195024
2865993519320
Python for Beginners
<class 'str'>


In [1]:
a=20
print(id(a))
a=40
print(id(a))

1379233392
1379234032


In [8]:
is_published = True
type(is_published)

bool

In THE above example : 
• price is an integer (a whole number without a decimal point)
• rating is a float (a number with a decimal point)
• course_name is a string (a sequence of characters)
• is_published is a boolean. Boolean values can be True or False. 

# comments

We use comments to add notes to our code. Good comments explain the hows and
whys, not what the code does. That should be reflected in the code itself. Use
comments to add reminders to yourself or other developers, or also explain your
assumptions and the reasons you’ve written code in a certain way. 

In [9]:
# This is a comment and it won’t get executed.
# Our comments can be multiple lines. 

# Receiving Input 


We can receive input from the user by calling the input() function. 

In [4]:
birth_year = int(input('Birth year: '))
print (birth_year)
present_year=2019
print('Your age :',present_year-birth_year)

Birth year: 1996
1996
Your age : 23


In [12]:
weight_pounds=float(input('Weight (lbs):'))
weight_kg=weight_pounds*0.45
print(weight_kg ," Kgs")

Weight (lbs):200
90.0  Kgs


The input() function always returns data as a string. So, we’re converting the
result into an integer by calling the built-in int() function. 

# Strings 

We can define strings using single (‘ ‘) or double (“ “) quotes.
To define a multi-line string, we surround our string with tripe quotes (“””).
We can get individual characters in a string using square brackets []. 

In [17]:
#multiline strings 
courses="""
ghsdfh
hgacx"""
print(courses)


ghsdfh
hgacx


In [89]:
'spam eggs'  # single quotes

'spam eggs'

In [18]:
'doesn\'t'  # use \' to escape the single quote...

"doesn't"

In [91]:
 "doesn't"  # ...or use double quotes instead

"doesn't"

In [92]:
'"Yes," they said.'

'"Yes," they said.'

In [93]:
"\"Yes,\" they said."

'"Yes," they said.'

In [94]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

In [2]:
s = 'First line.\nSecond line.'  # \n means newline
print(s)


First line.
Second line.


In [4]:
s

'First line.\nSecond line.'

In [5]:
# If you don’t want characters prefaced by \ to be interpreted as special characters, you can use raw strings by adding an r before the first quote:
print('C:\some\name')  # here \n means newline!
print(r'C:\some\name')  # note the r before the quote

C:\some
ame
C:\some\name


String literals can span multiple lines. One way is using triple-quotes: """...""" or '''...'''. End of lines are automatically included in the string, but it’s possible to prevent this by adding a \ at the end of the line. The following example:

In [20]:
print("""\
a
s
b
""")
#produces the following output (note that the initial newline is not included):

a
s
b



In [109]:
# Strings can be concatenated (glued together) with the + operator, and repeated with *:
3 * 'un' + 'ium'

'unununium'

In [8]:
# Two or more string literals (i.e. the ones enclosed between quotes) next to each other are automatically concatenated.
'Py' 'thon'

'Python'

In [119]:
text = ('Put several strings within parentheses '
        'to have them joined together.')
text

'Put several strings within parentheses to have them joined together.'

In [120]:
# This only works with two literals though, not with variables or expressions:
prefix = 'Py'
prefix 'thon'  # can't concatenate a variable and a string literal    

SyntaxError: invalid syntax (<ipython-input-120-84d39d0e215d>, line 3)

In [21]:
 ('un' * 3)+ 'ium'

'unununium'

In [124]:
# If you want to concatenate variables or a variable and a literal, use +:
prefix = 'Py'
prefix + 'thon'

'Python'

In [15]:
course = 'Python for Beginners'
type(course)

str

In [17]:
#Strings can be indexed (subscripted), with the first character having index 0. There is no separate character type; a character is simply a string of size one:
course[0] # returns the first character

'P'

In [18]:
course[1]  # returns the second character

'y'

In [19]:
#Indices may also be negative numbers, to start counting from the right:
course[-1] # returns the first character from the end 

's'

In [20]:
# Note that since -0 is the same as 0, negative indices start from -1.
course[-2] # returns the second character from the end

'r'

We can slice a string using a similar notation:

In [21]:
#In addition to indexing, slicing is also supported. While indexing is used to obtain individual characters, slicing allows you to obtain substring:
course[1:5] 

'ytho'

The above expression returns all the characters starting from the index position of 1
to 5 (but excluding 5). The result will be ytho 


If we leave out the start index, 0 will be assumed.
If we leave out the end index, the length of the string will be assumed. 


In [11]:
course[0:]

'Python for Beginners'

In [13]:
print (len(course))
print(course[0:])

20
Python for Beginners


In [128]:
course[-2:]  # characters from the second-last (included) to the end

'rs'

In [17]:
print(course[1:-1])

ython for Beginner


In [127]:
# Note how the start is always included, and the end always excluded. This makes sure that s[:i] + s[i:] is always equal to s:
course[:2] + course[2:]
# course[:4]+course[4:]


'Python for Beginners'

In [16]:
another=course[:]
print(another)

Python for Beginners


In [129]:
#Attempting to use an index that is too large will result in an error:
course[42]  # the word only has 6 characters

IndexError: string index out of range

In [139]:
# However, out of range slice indexes are handled gracefully when used for slicing:
course[0:42] 

'Python for Beginners'

In [140]:
course[42:]

''

Python strings cannot be changed — they are immutable. Therefore, assigning to an indexed position in the string results in an error:

In [141]:
course[0]='j'

TypeError: 'str' object does not support item assignment

In [143]:
# If you need a different string, you should create a new one:
'J' + course[1:]

'Jython for Beginners'

In [144]:
 course[:2] + 'py'

'Pypy'

### The built-in function len() returns the length of a string:

In [145]:
 s = 'supercalifragilisticexpialidocious'
len(s)    

34

### We can use formatted strings to dynamically insert values into our strings: 

In [59]:
first = 'John'
last='smith'
message = f'Hi, my name is {first} {last} {len(first)}  {2+3}'
print(message)
print(len(message))

Hi, my name is John smith 4  5
30


## String Methods

In [7]:
message=message.upper() # to convert to uppercase
print(message)

HI, MY NAME IS JASKIRAT SINGHJASKIRAT SINGH


In [35]:
print(message.lower()) # to convert to lowercase

'hi, my name is jaskirat singh'

In [36]:
message.title() # to capitalize the first letter of every word

'Hi, My Name Is Jaskirat Singh'

In [41]:
message.find('a') # returns the index of the first occurrence of a
                    # (or -1 if not found) 

8

In [42]:
find=message.find('z')

-1

In [60]:
message1=message.replace('i', 'e')
print(message1)
print(message)

He, my name es John smeth 4  5
Hi, my name is John smith 4  5


In [47]:
message

'Hi, my name is Jaskirat Singh'

In [62]:
print("John" in message)
print("John" not in message)

True
False


In [17]:
myStr = "         my nAME Is Tim       "

print(myStr.strip())  # -> "my nAME Is Tim"
print(myStr.split())  # -> ["my", "nAME", "Is", "Tim"]
print(myStr.lower())  # -> "    my name is tim"
print(myStr.upper())  # -> "    MY NAME IS TIM"
print(len(myStr))     # -> 18

my nAME Is Tim
['my', 'nAME', 'Is', 'Tim']
         my name is tim       
         MY NAME IS TIM       
30


In [ ]:
# we want the user to be able to type any variation of tim and be told that they are correct
# if we don't convert everything into lower cases that means if the user types "Tim"
# they'll be told that they got it wrong
# same goes for spaces, if the user clicks space before or after they type "tim"
# we still want to tell them they got the correct answer
answer = input("What is my name? ")

if answer.lower().strip() == "tim":
    print("Correct!")
else:
    print("That is incorrect!")

In [18]:
# This function checks to see if every element in a list is a zero
# It returns to us a True or False value depending on the list it's given
def isZeros(li):    
    for element in li:
        if element != 0:
            return False
    return True
print(isZeros([0,0,0,1]))  # This will print False


False


## To check if a string contains a character (or a sequence of characters), we use the in operator

In [51]:
contains = 'Python' in course

In [52]:
print(contains)

True


## Arithmetic Operations

In [59]:
2+3

5

In [60]:
2-3.1

-1.1

In [61]:
2/3

0.6666666666666666

In [64]:
4**2  # 4 to the power of 2

16

In [63]:
4%2  # the % operator returns the remainder of the division

0

In [62]:
2//3   #floor division discards the fractional part

0

## Augmented assignment operator: 

In [23]:
x=1
x = x + 10
print(x)

11


In [24]:
x-=3
print(x)

8


In [25]:
x += 10
print(x)

18


## Operator Precedence

Operator precedence:
1. parenthesis
2. exponentiation
3. multiplication / division
4. addition / subtraction 

In [26]:
print((50 - 5*6) / 4)

5.0


In [27]:
 print(50 - 5*6)

20


In [29]:
print((2+3)*10-3)

47


In [30]:
print(10+3*2**2)

22


In [70]:
#There is full support for floating point; operators with mixed type operands convert the integer operand to floating point:
4 * 3.75 - 1    

14.0

In [12]:
x=2.559
print(round(x,2))

2.56


In [35]:
print(abs(-2.9))

2.9


In [37]:
import math
print(math.ceil(2.1))
print(math.floor(2.1))

3
2


In [38]:
width = 20
height = 5 * 9
print(width * height)

900


##### If a variable is not “defined” (assigned a value), trying to use it will give you an error:

In [72]:
n

NameError: name 'n' is not defined

### In interactive mode, the last printed expression is assigned to the variable _. This means that when you are using Python as a desk calculator, it is somewhat easier to continue calculations, for example:

In [85]:
tax = 12.5 / 100
print(tax)

0.125


In [86]:
price = 100.50
price * tax

12.5625

In [87]:
 price + _

113.0625

In [88]:
round(_, 3)

113.062

In [ ]:
#If Statements
is_hot=True
is_cold=False
if is_hot:
 print('hot day')
elif is_cold:
 print('cold day')
else:
 print('beautiful day') 

## Price of a house is 1Million . If a buyer has good credit, they need to put down 10% otherwise they need to put down 20%  print the down Payment

In [1]:
a=10
print(id(a))
a=20
print(id(a))

1379233072
1379233392


In [9]:
price=1000000
has_good_credit=input('enter the credit:')
if has_good_credit== 'True':
    down_payment1=0.1*price
    print(f"Down Payment: ${down_payment1}")
    pass

if has_good_credit=='False':
    down_payment2=0.2*price
    print(f"Down Payment: ${down_payment2}")
    pass


enter the credit:False
Down Payment: $200000.0


## if applicant has high income And good credit and not has criminal record then eligible for loan 

## ahdvcsgd

In [20]:
a1=input('Enter the input :')
if bool(a1):
    print('amschv')
    pass
if not bool(a1):
    print('nsgdvha')

Enter the input :False
amschv


In [45]:
has_high_income=True
has_good_credit=True
has_criminal_reacord=False
if has_high_income and has_good_credit and not has_criminal_record:
    print("Eligible for loan")
    pass


Eligible for loan


## if temperature is greater than 30 it's a hot day otherwise if it's less than 10 it's a cold day otherwise it's neither hot nor cold

In [3]:
temperature=int(input('enter the temperature:'))
if temperature > 30:
    print("It's a hot day ")
    pass
elif temperature < 10:
    print("It's a cold day")
    pass
else:
    print("it's neither hot nor cold")
    pass
    

enter the temperature:5
It's a cold day


## Guess a Number

In [56]:
secret_number=9
guess_limit=3
guess_count=0
while guess_count < guess_limit:
    guess=int(input('Guess:'))
    guess_count+=1
    if guess == secret_number:
        print('You Won')
        break
        
else:
    print('Sorry,you failed!')
     

Guess:21
Guess:12
Guess:9
You Won


## Car Start ,Stop,Help,Quit

In [4]:
command=""
started=False
while True :
    command = input(">").lower()
    if command == "start":
        if started:
            print("Car is already started")
            pass
        else:
            started=True
            print("Car started ")
            pass
        pass
    elif command=="stop":
        if not started:
            print("Car is already stopped!")
            pass
        else:
            started=False
            print("Car stopped.")
            pass
        pass
    elif command=="help":
        print("""\
        start-to start the car
        stop-to stop the car
        quit-to quit
        """)
        pass
    elif command =="quit":
        break
        pass
    else:
        print('sorry i don\'t understand your language')
    
    

>start
Car started 
>start
Car is already started
>stop
Car stopped.
>stop
Car is already stopped!
>help
        start-to start the car
        stop-to stop the car
        quit-to quit
        
>quit


In [97]:
numbers=[3,6,2,8,4,10]
max=numbers[0]
for number in numbers:
    if number > max:
        max=number
        pass
    pass
print(max)

10


### Email Verification

In [2]:
email = input("Email Address: ")

if email.count("@") == 1 and len(email) >= 5:
    if email.find(".com") == len(email) - 4:
        print("Valid Email")
    else:
        print("Invalid Email, must end with .com")
else:
    print("Invalid Email, must contain one @ and be longer than 5 characters")

Email Address: abc@gmail.com
Valid Email


### Lists

Python knows a number of compound data types, used to group together other values. The most versatile is the list, which can be written as a list of comma-separated values (items) between square brackets. Lists might contain items of different types, but usually the items all have the same type.

In [9]:
squares = [1, 4, 9, 16, 25]
print(squares)

[1, 4, 9, 16, 25]


Like strings (and all other built-in sequence types), lists can be indexed and sliced:

In [10]:
print(squares[0])  # indexing returns the item

1


In [11]:
print(squares[-1])

25


In [12]:
 squares[-3:]  # slicing returns a new list

[9, 16, 25]

All slice operations return a new list containing the requested elements. This means that the following slice returns a new (shallow) copy of the list:

In [14]:
print(squares[:])

[1, 4, 9, 16, 25]


In [15]:
# Lists also support operations like concatenation:
print(squares + [36, 49, 64, 81, 100])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


Unlike strings, which are immutable, lists are a mutable type, i.e. it is possible to change their content:

In [16]:
cubes = [1, 8, 27, 65, 125]  # something's wrong here
# the cube of 4 is 64, not 65!
cubes[3] = 64  # replace the wrong value
print(cubes)

[1, 8, 27, 64, 125]


You can also add new items at the end of the list, by using the append() method (we will see more about methods later):

In [19]:
cubes.append(216)  # add the cube of 6
cubes.append(7 ** 3)  # and the cube of 7
print(cubes)

[1, 8, 27, 64, 125, 216, 343, 216, 2, 216, 2.3333333333333335]


Assignment to slices is also possible, and this can even change the size of the list or clear it entirely:

In [20]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print(letters)

['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [164]:
 # replace some values
letters[2:5] = ['C', 'D', 'E']
print(letters)

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [21]:
 # now remove them
letters[2:5] = []
print(letters)

['a', 'b', 'f', 'g']


In [166]:
# clear the list by replacing all the elements with an empty list
letters[:] = []
print(letters)

[]

In [22]:
#The built-in function len() also applies to lists:
letters = ['a', 'b', 'c', 'd']
len(letters)

4

In [23]:
# It is possible to nest lists (create lists containing other lists), for example:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
print(x)

[['a', 'b', 'c'], [1, 2, 3]]


In [170]:
print(x[0])

['a', 'b', 'c']

In [24]:
print(x[0][1])

b


## First Steps Towards Programming

#### Of course, we can use Python for more complicated tasks than adding two and two together. For instance, we can write an initial sub-sequence of the Fibonacci series as follows:

In [172]:
 # Fibonacci series:
     # the sum of two elements defines the next
a,b=0,1
while a < 10:
    print(a)
    a, b = b, a+b
    pass


0
1
1
2
3
5
8


This example introduces several new features.

The first line contains a multiple assignment: the variables a and b simultaneously get the new values 0 and 1. On the last line this is used again, demonstrating that the expressions on the right-hand side are all evaluated first before any of the assignments take place. The right-hand side expressions are evaluated from the left to the right.


The while loop executes as long as the condition (here: a < 10) remains true. In Python, like in C, any non-zero integer value is true; zero is false. The condition may also be a string or list value, in fact any sequence; anything with a non-zero length is true, empty sequences are false. The test used in the example is a simple comparison. The standard comparison operators are written the same as in C: < (less than), > (greater than), == (equal to), <= (less than or equal to), >= (greater than or equal to) and != (not equal to).

The body of the loop is indented: indentation is Python’s way of grouping statements. At the interactive prompt, you have to type a tab or space(s) for each indented line. In practice you will prepare more complicated input for Python with a text editor; all decent text editors have an auto-indent facility. When a compound statement is entered interactively, it must be followed by a blank line to indicate completion (since the parser cannot guess when you have typed the last line). Note that each line within a basic block must be indented by the same amount.

The print() function writes the value of the argument(s) it is given. It differs from just writing the expression you want to write (as we did earlier in the calculator examples) in the way it handles multiple arguments, floating point quantities, and strings. Strings are printed without quotes, and a space is inserted between items, so you can format things nicely, like this:

In [29]:
 i = 256*256
print('The value of i is ', i)

The value of i is  65536


The keyword argument end can be used to avoid the newline after the output, or end the output with a different string:

In [181]:
 a, b = 0, 1
while a < 1000:
    print(a, end=',')
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

## More Control Flow Tools

### if Statements

In [30]:
 x = int(input("Please enter an integer: "))
if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')
    

Please enter an integer: -1
Negative changed to zero


There can be zero or more elif parts, and the else part is optional. The keyword ‘elif’ is short for ‘else if’, and is useful to avoid excessive indentation. An if … elif … elif … sequence is a substitute for the switch or case statements found in other languages.

### for Statements

In [16]:
 # Measure some strings:
words = ['cat', 'window', 'defenestrate']
for w in words:
    print(w, len(w))
    print(type(w))

cat 3
<class 'str'>
window 6
<class 'str'>
defenestrate 12
<class 'str'>


If you need to modify the sequence you are iterating over while inside the loop (for example to duplicate selected items), it is recommended that you first make a copy. Iterating over a sequence does not implicitly make a copy. The slice notation makes this especially convenient:

In [192]:
for w in words[:]:  # Loop over a slice copy of the entire list.
     if len(w) > 6:
         words.insert(0, w)

print(words)

['defenestrate', 'cat', 'window', 'defenestrate']

With for w in words:, the example would attempt to create an infinite list, inserting defenestrate over and over again.

### The range() Function

If you do need to iterate over a sequence of numbers, the built-in function range() comes in handy. It generates arithmetic progressions:

In [31]:
print(range(5))

range(0, 5)


In [6]:

for i in range(1000000000000):
    print(i)

1
2
3
4
5


The given end point is never part of the generated sequence; range(10) generates 10 values, the legal indices for items of a sequence of length 10. It is possible to let the range start at another number, or to specify a different increment (even negative; sometimes this is called the ‘step’):

In [205]:
for i in range(5, 10):
    print (i,end=',')

5,6,7,8,9,

In [206]:
for i in range(0, 10, 3):
    print(i,end=',')

0,3,6,9,

In [3]:
prices=[10,20,30]
total=0
for price in prices:
    total+=price

print(f"total:{total}")

total:60


In [4]:
for i in range(-10, -100, -30):
    print(i,end=',')

-10,-40,-70,

To iterate over the indices of a sequence, you can combine range() and len() as follows:

In [208]:
a = ['Mary', 'had', 'a', 'little', 'lamb']
for i in range(len(a)):    
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In most such cases, however, it is convenient to use the enumerate() function, see Looping Techniques.

In [8]:
numbers=[2,2,2,2,5]
for x_count in numbers:
    output=''
    for count in range(x_count):
        output+='x'
        pass
    print(output)

xx
xx
xx
xx
xxxxx


In [96]:
for x in range(4):
    for y in range(3):
        print(f'({x},{y})')

(0,0)
(0,1)
(0,2)
(1,0)
(1,1)
(1,2)
(2,0)
(2,1)
(2,2)
(3,0)
(3,1)
(3,2)


### 2 dimensional list

In [101]:
matrix=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
matrix[0][1]=20
print(matrix[0][1])
print(matrix)
for row in matrix:
    for item in row:
        print(item,end=",")

20
[[1, 20, 3], [4, 5, 6], [7, 8, 9]]
1,20,3,4,5,6,7,8,9,

### Wap to remove the duplicates in a list

In [102]:
numbers=[1,2,2,3,4,5,5]
uniques=[]
for number in numbers:
    if number not in uniques:
        uniques.append(number)
        pass
    pass
print(uniques)

[1, 2, 3, 4, 5]


In [8]:
#enumerate(iterable, start=0)
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
print(list(enumerate(range(5))))

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]


A strange thing happens if you just print a range:

In [210]:
print(range(10))

range(0, 10)


In [211]:
list(range(5))

[0, 1, 2, 3, 4]

## break and continue Statements, and else Clauses on Loops

The break statement, like in C, breaks out of the innermost enclosing for or while loop.

Loop statements may have an else clause; it is executed when the loop terminates through exhaustion of the list (with for) or when the condition becomes false (with while), but not when the loop is terminated by a break statement. This is exemplified by the following loop, which searches for prime numbers:

In [220]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:  
        # loop fell through without finding a factor
        print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3


(Yes, this is the correct code. Look closely: the else clause belongs to the for loop, not the if statement.)

###### The continue statement, also borrowed from C, continues with the next iteration of the loop:

In [30]:
for num in range(2, 10):
    if num % 2 == 0:
        print("Found an even number", num)
        continue
    print("Found a number", num)      

Found an even number 2
Found a number 3
Found an even number 4
Found a number 5
Found an even number 6
Found a number 7
Found an even number 8
Found a number 9


##### pass Statements

The pass statement does nothing. It can be used when a statement is required syntactically but the program requires no action. For example:

In [223]:
while True:
    pass  # Busy-wai





t for keyboard interrupt (Ctrl+C)

This is commonly used for creating minimal classes:

In [1]:
class MyEmptyClass:
    pass

Another place pass can be used is as a place-holder for a function or conditional body when you are working on new code, allowing you to keep thinking at a more abstract level. The pass is silently ignored:

In [2]:
def initlog(*args):
    pass   # Remember to implement this!

## Defining Functions

We can create a function that writes the Fibonacci series to an arbitrary boundary:

In [19]:
def fib(n):    # write Fibonacci series up to n
    """Print a Fibonacci series up to n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
        pass
    
    pass
        
# Now call the function we just defined:
fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 

The keyword def introduces a function definition. It must be followed by the function name and the parenthesized list of formal parameters. The statements that form the body of the function start at the next line, and must be indented.

In [20]:
fib

<function __main__.fib(n)>

In [21]:
f = fib
f(100)

0 1 1 2 3 5 8 13 21 34 55 89 

In [22]:
fib(0)

In [11]:
print(fib(0))

None


In [17]:
# It is simple to write a function that returns a list of the numbers of the Fibonacci series, instead of printing it:
def fib2(n):  # return Fibonacci series up to n
    """Return a list containing the Fibonacci series up to n."""
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)    # see below
        a, b = b, a+b
    return result
    
f100 = fib2(100)    # call it
print(f100)                # write the result

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

This example, as usual, demonstrates some new Python features:

The return statement returns with a value from a function. return without an expression argument returns None. Falling off the end of a function also returns None.

The statement result.append(a) calls a method of the list object result. A method is a function that ‘belongs’ to an object and is named obj.methodname, where obj is some object (this may be an expression), and methodname is the name of a method that is defined by the object’s type. Different types define different methods. Methods of different types may have the same name without causing ambiguity. (It is possible to define your own object types and methods, using classes, see Classes) The method append() shown in the example is defined for list objects; it adds a new element at the end of the list. In this example it is equivalent to result = result + [a], but more efficient.

#### Problem: we want to ask a set of questions 5 times.


#### Below I will show you three ways of solving this problem and then we will compare their efficiency and elegance.

In [ ]:
name = input("Please type your name: ")
age = input("Please type your age: ")
country = input("Please type where you are from: ")
print("Your name is", name, "you are", age, " years old and you are from", country + '.')

name = input("Please type your name: ")
age = input("Please type your age: ")
country = input("Please type where you are from: ")
print("Your name is", name, "you are", age, "old and you are from", country + '.')

name = input("Please type your name: ")
age = input("Please type your age: ")
country = input("Please type where you are from: ")
print("Your name is", name, "you are", age, "old and you are from", country + '.')

name = input("Please type your name: ")
age = input("Please type your age: ")
country = input("Please type where you are from: ")
print("Your name is", name, "you are", age, "old and you are from", country + '.')

name = input("Please type your name: ")
age = input("Please type your age: ")
country = input("Please type where you are from: ")
print("Your name is", name, "you are", age, "old and you are from", country + '.')

In [23]:
def askQuestions():
    name = input("Please type your name: ")
    age = input("Please type your age: ")
    country = input("Please type where you are from: ")
    print("Your name is", name, "you are", age, "old and you are from", country + '.')

askQuestions() #1
askQuestions() #2
askQuestions() #3
askQuestions() #4
askQuestions() #5

Please type your name: jqhwsbdj
Please type your age: sbcjb
Please type where you are from: ajshb
Your name is jqhwsbdj you are sbcjb old and you are from ajshb.
Please type your name: j
Please type your age: mansbx
Please type where you are from: nBSVX
Your name is j you are mansbx old and you are from nBSVX.
Please type your name: MNBNMSX
Please type your age: MSXBN
Please type where you are from: AMSBXNMSB 
Your name is MNBNMSX you are MSXBN old and you are from AMSBXNMSB .
Please type your name: AMSBMN
Please type your age: ASXBM
Please type where you are from: ANSBNMB
Your name is AMSBMN you are ASXBM old and you are from ANSBNMB.
Please type your name: ASNBX NBA
Please type your age: ANSB XNABSX
Please type where you are from: ANSBXN
Your name is ASNBX NBA you are ANSB XNABSX old and you are from ANSBXN.


In [ ]:
def askQuestions():
    name = input("Please type your name: ")
    age = input("Please type your age: ")
    country = input("Please type where you are from: ")
    print("Your name is", name, "you are", years, "old and you are from", country + '.')

for i in range(5):
    askQuestions()  # This will call the function 5 times

In [9]:
def increment(number: int , by: int =1) -> tuple :
    return (number,number+by)
print(increment(2))

(2, 3)


### More on Defining Functions

It is also possible to define functions with a variable number of arguments. There are three forms, which can be combined.

#### Default Argument Values

In [32]:
def ask_ok(prompt, retries=4, reminder='Please try again!'):
    while True:
        ok = input(prompt)
        if ok in ('y', 'ye', 'yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('invalid user response')
        print(reminder)
print(ask_ok('Do you really want to quit?'))        

Do you really want to quit?yes
True


In [34]:
ask_ok('OK to overwrite the file?', 2)

OK to overwrite the file?asssdd
Please try again!
OK to overwrite the file?jhdcgj
Please try again!
OK to overwrite the file?jhgfh


ValueError: invalid user response

In [23]:
ask_ok('OK to overwrite the file?', 2, 'Come on, only yes or no!')

OK to overwrite the file?12
Come on, only yes or no!
OK to overwrite the file?yes


True

This example also introduces the in keyword. This tests whether or not a sequence contains a certain value.

The default values are evaluated at the point of function definition in the defining scope, so that

In [10]:
i = 5

def f(arg=i):
    print(arg)

i = 6
f()

5


Important warning: The default value is evaluated only once. This makes a difference when the default is a mutable object such as a list, dictionary, or instances of most classes. For example, the following function accumulates the arguments passed to it on subsequent calls:

In [28]:
def f(a, L=[]):
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

[1]
[1, 2]
[1, 2, 3]


If you don’t want the default to be shared between subsequent calls, you can write the function like this instead:

In [29]:
def f(a, L=None):
    if L is None:
        L = []
    L.append(a)
    return L
print(f(1))
print(f(2))
print(f(3))

[1]
[2]
[3]


### Keyword Arguments

Functions can also be called using keyword arguments of the form kwarg=value. For instance, the following function:

In [13]:
def parrot(voltage, state='a stiff', action='voom'):
    print( action,voltage,state)
    
#accepts one required argument (voltage) and three optional arguments (state, action, and type). This function can be called in any of the following ways:    
parrot('1000')                                          # 1 positional argument
parrot(voltage=1000)                                  # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword    

voom 1000 Norwegian Blue a stiff
voom 1000 Norwegian Blue a stiff
VOOOOOM 1000000 Norwegian Blue a stiff
VOOOOOM 1000000 Norwegian Blue a stiff
jump a million Norwegian Blue bereft of life
voom a thousand Norwegian Blue pushing up the daisies


In a function call, keyword arguments must follow positional arguments. All the keyword arguments passed must match one of the arguments accepted by the function (e.g. actor is not a valid argument for the parrot function), and their order is not important. This also includes non-optional arguments (e.g. parrot(voltage=1000) is valid too). No argument may receive a value more than once. Here’s an example that fails due to this restriction:

In [31]:
def function(a):
    pass

function(0, a=0)

TypeError: function() got multiple values for argument 'a'

 No argument may receive a value more than once. Here’s an example that fails due to this restriction:

When a final formal parameter of the form ** name is present, it receives a dictionary (see Mapping Types — dict) containing all keyword arguments except for those corresponding to a formal parameter. This may be combined with a formal parameter of the form *name (described in the next subsection) which receives a tuple containing the positional arguments beyond the formal parameter list. (*name must occur before **name.) For example, if we define a function like this:

### *args

In [92]:
def multiply(*numbers):
    print(numbers)
    total=1
    for number in numbers:
        total*=number
    return total    
    
print(multiply(2,3,4,5))    

(2, 3, 4, 5)
120


### **args

In [91]:
def save_user(**user):
    print(user)
    print(type(user))
    print(user["id"])
    pass
save_user(id=1,name="admin")

{'id': 1, 'name': 'admin'}
<class 'dict'>
1


In [6]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    
    for arg in arguments:
        
        print(arg)
    print("-" * 40)
    
    for kw in keywords:
        print(kw, ":", keywords[kw])
        
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")        

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
<class 'str'>
client : John Cleese
<class 'str'>
sketch : Cheese Shop Sketch
<class 'str'>


Note that the order in which the keyword arguments are printed is guaranteed to match the order in which they were provided in the function call.

### Arbitrary Argument Lists

In [94]:
def concat(*args, sep="/"):
    print(args)
    print(type(args))
    return sep.join(args)

concat("earth", "mars", "venus")

('earth', 'mars', 'venus')
<class 'tuple'>


'earth/mars/venus'

In [24]:
concat("earth", "mars", "venus", sep=".")

'earth.mars.venus'

### Unpacking Argument Lists

In [14]:
print(range(100000000009))
list(range(3, 6))         # normal call with separate arguments

range(0, 100000000009)


[3, 4, 5]

In [32]:
args = [3, 6]
print(range(*args))
list(range(*args))   # call with arguments unpacked from a list


range(3, 6)


[3, 4, 5]

In the same fashion, dictionaries can deliver keyword arguments with the ** operator:

In [46]:
def parrot(voltage, state='a stiff', action='voom'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.", end=' ')
    print("E's", state, "!")
d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}
parrot(**d)

-- This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !


### Lambda Functions

In python lambda stands for an anonymous function. It is used for creating small functions that are typically only used a few times. A lambda function can only perform one lines worth of operations on a given input. To declare a lambda function is similar to creating a variable.

The parameter(s) for a lambda function comes before the colon (in our case x) and what will be returned comes after (x+5). We can use our lambda function the same as a regular function.

Lambda functions can also use multiple parameters.

In [50]:
func = lambda x: x+5

print(func(2))
# Prints 7

7


In [51]:
#Lambda functions can also use multiple parameters.
func = lambda x, y: x+y

print(func(2,2))
# Prints 4

4


In [49]:
def make_incrementor(n):
    return lambda x: x + n

f = make_incrementor(42)
f(0)


42

In [50]:
f(1)

43

The above example uses a lambda expression to return a function. Another use is to pass a small function as an argument:

In [52]:
pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]
pairs.sort(key=lambda pair: pair[1])
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

## Comparison operators 

### Lists Methods

In [4]:
numbers = [1, 2, 3, 4, 5]

In [5]:
numbers.append(6) # adds 6 to the end
print(numbers)

[1, 2, 3, 4, 5, 6]


In [6]:
numbers.insert(0, 6) # adds 6 at index position of 0
print(numbers)

[6, 1, 2, 3, 4, 5, 6]


In [7]:
numbers.remove(6)  # removes 6 from the starting inde
print(numbers)

[1, 2, 3, 4, 5, 6]


In [8]:
print(numbers.pop())            # removes the last item
print(numbers)

6
[1, 2, 3, 4, 5]


In [43]:
print(numbers.index(5))

4


In [44]:
numbers.sort()
print(numbers)

[1, 2, 3, 4, 5]


In [45]:
numbers.reverse()
print(numbers)

[5, 4, 3, 2, 1]


In [46]:
print(numbers.count(1))

1


In [47]:
print(numbers.copy()) # returns a copy of the list

[5, 4, 3, 2, 1]


In [49]:
print(numbers.clear())
print(numbers)

None
[]


## Tuples
They are like read-only lists. We use them to store a list of items. But once we
define a tuple, we cannot add or remove items or change the existing items.
coordinates = (1, 2, 3)
We can unpack a list or a tuple into separate variables:
x, y, z = coordinates 

In [108]:
numbers=(1,2,3,1,2,3,4)
print(numbers.count(1))
print(numbers.index(1))
print(numbers[0])
numbers[0]=12

2
0
1


TypeError: 'tuple' object does not support item assignment

### Unpacking

In [112]:
coordinates=(1,2,3)
x,y,z=coordinates
print(x)
print(y)
coordinatesList=[1,2,3]
x,y,z=coordinatesList
print(x)

1
2
1


## Dictionaries 


In [113]:
customer = {
 'name': 'John Smith',
 'age': 30,
 'is_verified': True
}
print(customer['name'])  # returns “John Smith”


John Smith


In [62]:
customer['type'] # throws an error 
customer['Name']

KeyError: 'type'

In [114]:
customer.get('birthdate', 'silver') # returns “silver”

'silver'

In [115]:
customer['name'] = 'jack smith'
print(customer['name'])

jack smith


In [116]:
customer["birthdate"]="Jan 1 1980"
print(customer)

{'name': 'jack smith', 'age': 30, 'is_verified': True, 'birthdate': 'Jan 1 1980'}


In [15]:
phone=input("Phone :")
digits_mapping={
    "1":"One",
    "2":"Two",
    "3":"Three",
    "4":"Four"
}
output=""
for ch in phone :
    output+=digits_mapping.get(ch,"!")+" "
    pass
print(output)

Phone :1234a
One Two Three Four ! 


In [70]:
def greet_user(name):
    print(f'Hi {name}')
          
greet_user('John')

Hi John


In [82]:
# Two positional arguments
def greet_user(name1,name2):
    print(name1,name2)
greet_user("John", 'Smith')

John Smith


In [83]:
# Keyword arguments
def calculate_total(order,shipping,tax):
    print (order+shipping+tax)
calculate_total(order=50, shipping=5, tax=0.1)

55.1


Our functions can return values. If we don’t use the return statement, by default
None is returned. None is an object that represents the absence of a value. 

In [126]:
def square(number):
    return number * number
result = square(2)
print(result) # prints 4

4


### Exceptions 

Exceptions are errors that crash our programs. They often happen because of bad
input or programming errors. It’s our job to anticipate and handle these exceptions
to prevent our programs from cashing. 

### Catching Errors

In [129]:
print("I will add 5 to any number you give me.")
num = input("type a number:")

addedNum = int(num) + 5
print("5 +", num, "is", addedNum)

I will add 5 to any number you give me.
type a number:a


ValueError: invalid literal for int() with base 10: 'a'

In [131]:
print("I will add 5 to any number you give me.")
num = input("type a number:")
try:
    addedNum = int(num) + 5
    print("5 +", num, "is", addedNum)
except:
    print("That is not a number!!")

I will add 5 to any number you give me.
type a number:a
That is not a number!!


In [127]:
try:
 age = int(input('Age: '))
 income = 20000
 risk = income / age
 print(age)
 print(risk)
except ValueError:
 print('Not a valid number')
except ZeroDivisionError:
 print('Age cannot be 0')


Age: a
Not a valid number


## Classes 

We use classes to define new types. 


In [134]:
class Point:
    def __init__(self, x, y):   #methods
        
        self.x = x
        self.y = y
        
    def printAdd(self):
        print('Addition:',self.x+self.y) 
        
pt=Point(2,3)   
pt.printAdd()
print(pt.x,pt.y)

Addition: 5
2 3


When a function is part of a class, we refer to it as a method. 

Classes define templates or blueprints for creating objects. An object is an instance
of a class. Every time we create a new instance, that instance follows the structure
we define using the class. 

__init__ is a special method called constructor. It gets called at the time of
creating new objects. We use it to initialize our objects. 

## Inheritance 


Inheritance is a technique to remove code duplication. We can create a base class
to define the common methods and then have other classes inherit these methods. 

In [1]:
class Mammal:
    def walk(self):
        print('walk')
class Dog(Mammal):
    def bark(self):
        print('bark')          
dog = Dog()
dog.walk() # inherited from Mammal     
dog.bark() # defined in Dog 

walk
bark


## Modules 

A module is a file with some Python code. We use modules to break up our
program into multiple files. This way, our code will be better organized. We won’t
have one gigantic file with a million lines of code in it!
There are 2 ways to import modules: we can import the entire module, or specific
objects in a module. `

In [4]:
# importing the entire converters module
import numpy


In [5]:
# importing one function in the sklearn module
from sklearn import preprocessing


## Packages 

A package is a directory with __init__.py in it. It can contain one or more
modules. 

In [6]:
# importing the entire sales module
from ecommerce import sales
sales.calc_shipping()


ModuleNotFoundError: No module named 'ecommerce'

## Python Standard Library


Python comes with a huge library of modules for performing common tasks such as
sending emails, working with date/time, generating random values, etc. 

##### Random Module

In [135]:
import random
for i in range(3):
    print(random.random())       # returns a float between 0 to 1


0.3834443557480389
0.9266118777538608
0.39957609211276124


In [43]:
random.randint(1,6)     # returns an int between 1 to 6 

4

In [136]:
members=['John','Bob','Mary']
leader=random.choice(members)   # randomly picks an item
leader

'Bob'

In [143]:
import random
class Dice:
    def roll(self):
        first=random.randint(1,6)
        second=random.randint(1,6)
        return first,second
    pass

dice=Dice()
print(dice.roll())
    

(6, 3)


## Pypi 

Python Package Index (pypi.org) is a directory of Python packages published by
Python developers around the world. We use pip to install or uninstall these
packages. 

In [16]:
#pip install openpyxl


### Documentation Strings

In [35]:
def my_function():
    """Do nothing, but document it.
     No, really, it doesn't do anything.
     """
    pass
print(my_function.__doc__)

Do nothing, but document it.
     No, really, it doesn't do anything.
     


### An example that uses most of the list methods:

In [1]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits.count('apple')

2

In [19]:
fruits.count('tangerine')

0

In [20]:
fruits.index('banana')

3

In [21]:
fruits.index('banana', 4)  # Find next banana starting a position 4

6

In [22]:
fruits.reverse()
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [24]:
fruits.append('grape')
fruits

['banana',
 'apple',
 'kiwi',
 'banana',
 'pear',
 'apple',
 'orange',
 'grape',
 'grape']

In [3]:
fruits.sort()

None


In [4]:
fruits

['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear']

In [5]:
fruits.pop()

'pear'

You might have noticed that methods like insert, remove or sort that only modify the list have no return value printed – they return the default None.

In [28]:
fruits.insert(0,'watermelon')

In [29]:
fruits

['watermelon',
 'apple',
 'apple',
 'banana',
 'banana',
 'grape',
 'grape',
 'kiwi',
 'orange']

In [30]:
fruits.remove('watermelon')

In [31]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'grape', 'kiwi', 'orange']

In [34]:
fruits.pop(1)

'apple'

In [35]:
fruits

['apple', 'banana', 'banana', 'grape', 'grape', 'kiwi', 'orange']

In [37]:
fruits1=fruits.copy()

In [38]:
fruits.clear()

In [39]:
fruits


[]

In [40]:
fruits1

['apple', 'banana', 'banana', 'grape', 'grape', 'kiwi', 'orange']

### Using Lists as Stacks

The list methods make it very easy to use a list as a stack, where the last element added is the first element retrieved (“last-in, first-out”). To add an item to the top of the stack, use append(). To retrieve an item from the top of the stack, use pop() without an explicit index. For example:

In [43]:
stack=[3,4,5]
stack.append(6)
stack.append(7)
stack

[3, 4, 5, 6, 7]

In [44]:
stack.pop()

7

In [45]:
stack

[3, 4, 5, 6]

In [46]:
stack.pop()

6

In [47]:
stack

[3, 4, 5]

### Using Lists as Queues

It is also possible to use a list as a queue, where the first element added is the first element retrieved (“first-in, first-out”); however, lists are not efficient for this purpose. While appends and pops from the end of list are fast, doing inserts or pops from the beginning of a list is slow (because all of the other elements have to be shifted by one).

To implement a queue, use collections.deque which was designed to have fast appends and pops from both ends. For example:

In [51]:
from collections import deque
queue=deque(["Eric","John","Michael"])
queue.append("Terry")   # Terry arrives
queue.append("Graham") 
# Graham arrives
queue

deque(['Eric', 'John', 'Michael', 'Terry', 'Graham'])

In [52]:
queue.popleft()         # The first to arrive now leaves


'Eric'

In [53]:
queue

deque(['John', 'Michael', 'Terry', 'Graham'])

In [54]:
queue.popleft()         # The second to arrive now leaves

'John'

In [55]:
queue

deque(['Michael', 'Terry', 'Graham'])

### List Comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

In [57]:
# For example, assume we want to create a list of squares, like:
square=[]
for x in range(10):
    square.append(x**2)
    pass
square
    

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Note that this creates (or overwrites) a variable named x that still exists after the loop completes. We can calculate the list of squares without any side effects using:

In [58]:
squares = list(map(lambda x: x**2, range(10)))

In [59]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

which is more concise and readable.

A list comprehension consists of brackets containing an expression followed by a for clause, then zero or more for or if clauses. The result will be a new list resulting from evaluating the expression in the context of the for and if clauses which follow it. For example, this listcomp combines the elements of two lists if they are not equal:

In [60]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

and it’s equivalent to:

In [62]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))
            pass
        pass
    pass
combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

Note how the order of the for and if statements is the same in both these snippets.

In [63]:
vec=[-4,-2,0,2,4]
# create a new list with the values doubled
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [64]:
## filter the list to exclude negative numbers
[x for x in vec if x >=0]

[0, 2, 4]

In [65]:
# apply a function to all the elements
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [66]:
# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [68]:
# # create a list of 2-tuples like (number, square)
[(x,x**2) for x in range (6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [69]:
# the tuple must be parenthesized, otherwise an error is raised
 [x, x**2 for x in range(6)]

IndentationError: unexpected indent (<ipython-input-69-ccdc37b0e1e3>, line 2)

In [70]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

List comprehensions can contain complex expressions and nested functions:

In [71]:
from math import pi
[str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

## Nested List Comprehensions

The initial expression in a list comprehension can be any arbitrary expression, including another list comprehension.

Consider the following example of a 3x4 matrix implemented as a list of 3 lists of length 4:

In [72]:
 matrix = [
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
 ]

The following list comprehension will transpose rows and columns:

In [16]:
matrix = [
     [1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12],
 ]
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [74]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])
    pass
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

which, in turn, is the same as:

In [75]:
transposed = []
for i in range(4):
     # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [77]:
# In the real world, you should prefer built-in functions to complex flow statements. The zip() function would do a great job for this use case:


In [78]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

## The del statement

There is a way to remove an item from a list given its index instead of its value: the del statement. This differs from the pop() method which returns a value. The del statement can also be used to remove slices from a list or clear the entire list (which we did earlier by assignment of an empty list to the slice). For example:

In [80]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
a

[1, 66.25, 333, 333, 1234.5]

In [81]:
del a[2:4]

In [82]:
a

[1, 66.25, 1234.5]

In [83]:
del a[:]
a

[]

del can also be used to delete entire variables:

In [84]:
del a

In [85]:
a

NameError: name 'a' is not defined

## Tuples and Sequences

We saw that lists and strings have many common properties, such as indexing and slicing operations. They are two examples of sequence data types (see Sequence Types — list, tuple, range). Since Python is an evolving language, other sequence data types may be added. There is also another standard sequence data type: the tuple.

A tuple consists of a number of values separated by commas, for instance:

In [3]:
t = (12345, 54321, 'hello!')
t[0]


12345

In [7]:
t

(12345, 54321, 'hello!')

In [4]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
u
print(type(u))

<class 'tuple'>


In [92]:
# Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [93]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
v

([1, 2, 3], [3, 2, 1])

In [9]:
empty = ()
len(empty)

0

In [5]:
l=[1,2,3]
tuple=1,2,3,4
tuple1=l,tuple
print(tuple1)
singleton='hello', 
len(singleton)

([1, 2, 3], (1, 2, 3, 4))


1

In [96]:
singleton

('hello',)

The statement t = 12345, 54321, 'hello!' is an example of tuple packing: the values 12345, 54321 and 'hello!' are packed together in a tuple. The reverse operation is also possible:

In [98]:
t = 12345, 54321, 'hello!' 
t

(12345, 54321, 'hello!')

In [102]:
x, y, z = t
y

54321

This is called, appropriately enough, sequence unpacking and works for any sequence on the right-hand side. Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence. Note that multiple assignment is really just a combination of tuple packing and sequence unpacking.


## Sets

Python also includes a data type for sets. A set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the set() function can be used to create sets. Note: to create an empty set you have to use set(), not {}; the latter creates an empty dictionary, a data structure that we discuss in the next section.

In [103]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)    # show that duplicates have been removed


{'banana', 'orange', 'pear', 'apple'}


In [104]:
'orange' in basket     # fast membership testing


True

In [105]:
'watermelon' in basket

False

##### Demonstrate set operations on unique letters from two words

In [107]:
a = set('abracadabra')
a    # unique letters in a

{'a', 'b', 'c', 'd', 'r'}

In [108]:
b = set('alacazam')
b

{'a', 'c', 'l', 'm', 'z'}

In [109]:
a - b    # letters in a but not in b

{'b', 'd', 'r'}

In [110]:
a | b            # letters in a or b or both

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [111]:
 a & b            # letters in both a and b

{'a', 'c'}

In [112]:
 a ^ b          # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

Similarly to list comprehensions, set comprehensions are also supported:

In [113]:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

## Dictionaries

In [114]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [115]:
tel['jack']

4098

In [116]:
del tel['sape']

In [117]:
tel

{'jack': 4098, 'guido': 4127}

In [118]:
list(tel)

['jack', 'guido']

In [119]:
sorted(tel)

['guido', 'jack']

In [120]:
'guido' in tel

True

In [121]:
'jack' not in tel

False

The dict() constructor builds dictionaries directly from sequences of key-value pairs:

In [122]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [123]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [124]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

## Looping Techniques

When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the items() method.

In [125]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k,v)
    

gallahad the pure
robin the brave


 When looping through a sequence, the position index and corresponding value can be retrieved at the same time using the enumerate() function.

In [127]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i,v)

0 tic
1 tac
2 toe


To loop over two or more sequences at the same time, the entries can be paired with the zip() function.

In [7]:
list1=[1,2,3,4,5,6]
list2=['one','two','three','four','five']
#Python 2 zipped=zip(list1,list2)1
zipped=list(zip(list1,list2))
print(zipped)
unzipped=list(zip(*zipped))
print(unzipped)

[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')]
[(1, 2, 3, 4, 5), ('one', 'two', 'three', 'four', 'five')]


In [128]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the reversed() function.

In [129]:
 for i in reversed(range(1, 10, 2)):
        print(i)

9
7
5
3
1


To loop over a sequence in sorted order, use the sorted() function which returns a new sorted list while leaving the source unaltered.

In [130]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


It is sometimes tempting to change a list while you are looping over it; however, it is often simpler and safer to create a new list instead.

In [131]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)
        pass
    pass
filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

## Fibonacci Series

In [132]:
# Fibonacci numbers module

def fib(n):    # write Fibonacci series up to n
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

def fib2(n):   # return Fibonacci series up to n
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)
        a, b = b, a+b
    return result

ModuleNotFoundError: No module named 'fibo'

SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello')? (<ipython-input-136-5a1ef41e7057>, line 1)