## Бизли2  

In [ ]:
публикация на русском канале с 12 января 2024 г

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#1+ 12 янв 2024

Какая библиотека позволяет отлавливать и генерировать события клика и движения мышки?

In [ ]:
mss
pillow
pytorch
pynput #
watchdog

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#2+

Какое наибольшее целое число может быть в переменной?

In [ ]:
2**32-1
2**64-1
2**52-1
2**256-1
2**1024-1
Ограничено только памятью компьютера #

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#3+

In [ ]:
Что выведет код?

In [1]:
import datetime
t1 = datetime.date(2021, 3, 5) - datetime.date(2021, 2, 23)
t2 = datetime.date(2020, 3, 5) - datetime.date(2020, 2, 23)
print((t2 - t1).days)

1


In [ ]:
-1
0
1 #
5
10
11
23
ValueError
TypeError

In [ ]:
Лампочка

In [ ]:
t1 = 2021-03-05 - 2021-02-23 = 10 дней
t2 = 2020-03-05 - 2020-02-23 = 11 дней
Разница между t2 и t1 составляет 11 - 10 = 1 день. Так как t2 больше t1, код выведет 1

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#4+

In [2]:
import hashlib
m = hashlib.sha256()
m.update(b"hello")
print(m.digest_size, len(m.hexdigest()))

32 64


In [ ]:
5 5
5 10
32 32
32 64  #
256 256
256 512

m.digest_size - размер хеша в байтах, для SHA-256 это 32 байта
m.hexdigest() - 16-ричное представление хеша, каждый байт кодируется двумя 16-ричными символами (в 2 раза больше размера хеша)


In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#5+

Какую функцию стоит использовать для генерации криптографически надежных (псевдо)случайных элементов?

In [ ]:
os.urandom(1)  #
random.random()
random.uniform(0, 1)
id(0)

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#6+

In [7]:
x = (i**2 for i in range(1, 100) if not i % 3)
y = (i for i in x if not i % 5)
print(next(y))

225


In [ ]:
6
9
15
144 
196
225   #

Код создаёт два генератора, x вычисляет квадраты чисел от 1 до 99, кратных 3. y фильтрует x, оставляя только те, что кратны 5. Затем выводится первый элемент y, который равен 225.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#7+

In [4]:
def f(**x): 
    return sum(x.values())
s = f(a=1, b=2) + f(x=2, y=1, z=0)
print(s)

6


In [ ]:
(1, 2, 2, 1, 0)
{"a":1, "b":2, "x":2, "y":1, "z":0}
3
6   #
{1, 2, 2, 1, 0}
0

Код определяет функцию f, суммирующую значения именованных аргументов, и вычисляет сумму двух вызовов f. Выводится результат суммирования, который равен 6.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#8+

In [6]:
import time
time.asctime((2023, 2, 23, 12, 0, 0, 1, 0, 0))

'Tue Feb 23 12:00:00 2023'

In [ ]:
Feb 23 12:00:00 2023 Tue
Tue Feb 23 12:00:00 2023     #
Mon Feb 23 12:00:00 2023
23.02.2023
23-02-2023
Tue Feb 23 12:00 2023 
Mon Feb 23 12:00 2023
2021 Feb 23 12:00:00 Tue

Код использует функцию asctime из модуля time для форматирования кортежа, представляющего время, в строку. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#9  (23 февраля 2021)  24 января 2024 

In [9]:
import time
my_time = time.strptime("Mon Feb 22 10:55:00 2023")
my_time = time.strftime("%d.%m.%Y", my_time)
print(my_time)

22.02.2023


In [ ]:
22 Feb 2023
22.02.2023  #
22.02.23
2023.02.22
22-02-2023
Mon Feb 22 10:55:00 2023
Feb 22 2023
ValueError

Результат вызова функции strptime преобразует строку в структуру времени time.struct_time.
Затем strftime преобразует эту структуру в строку с заданным форматом даты

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
/////////////

In [ ]:
#10+

In [1]:
len(str(1 + 1) * int('1' + '1'))

11

In [ ]:
2
4
11  #
22
TypeError

1+1=2; "1"+"1"= "11"; "2"*11="22222222222"; длина строки: 11.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#11+

In [4]:
a, b = 5, 15
print(a == 5 == b / 3 == 4 + 1)

True


In [ ]:
True   #
False 
TypeError 
AttributeError
None

In [ ]:
5 == 5 == 15/3 == 4+1

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#12+

In [10]:
b, c, a = c, a, b = 1, 2, 3
print(a, b, c)

2 3 1


In [ ]:
1 2 3
2 3 1   #
3 1 2
1 3 2
2 1 3
3 2 1

Данное выражение эквивалентно двум строчкам b, c, a = 1, 2, 3; c, a, b = 1, 2, 3, последняя перезаписывает первую. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#13  17 феврвля 2021 

In [15]:
print(bool("0"), bool([0, None]), bool((None,)))

True True True


In [ ]:
False False False
False False True
False True True
True True True  #
True False False
True True False

In [ ]:
True True True, так как все объекты непустые

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
......///////////////

In [ ]:
#14+

In [2]:
keys = ["a", "b", "c", "d"]
values = [1, 2, 3, 4]
dict_ = {key: value for (key, value) in zip(keys, values)}
dict_ = {key: value for (key, value) in dict_.items() if value % 2 == 1}
sum([value for value in dict_.values()], 5)

9

In [ ]:
0
1
4
9  #
10
15

Код создает словарь с парами ключ-значение из списков keys и values, затем фильтрует его, оставляя только элементы со значениями-нечетными числами. К сумме всех значений в словаре добавляется 5. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#15+

In [3]:
2 ^ 1 << 1 | 1 & 1 << 1

0

In [5]:
0  #
1
2
3
4
True
False

True

С учетом правильного порядка приоритета операций, сначала выполняются сдвиги, затем побитовые операции AND, XOR и OR. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#16+

In [6]:
a = True
b= False
c = {True, False}
not b and b not in c or not a not in c

True

In [ ]:
True  #
False

not b = True;
b not in c = False;
not a not in c = True;
True and False or True = False or True = True

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#17+

In [9]:
2 ** -2 + -2 ** 2

-3.75

In [ ]:
-3.75   #
-0.5
0
3.75
4.25

In [ ]:
2 ^ -2 = 0.25;
-2 ^ 2 = -(2 ** 2) = -4;
0.25 + (-4) = -3.75


In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#18+

In [10]:
d = {}
print(d.get("a", 0) + d.setdefault("a", 10) + d.get("a", 0))

20


In [ ]:
0
10
20
30
TypeError
AttributeError

d.get("a", 0) вернет 0 (тк а нет в d). d.setdefault("a", 10) устанавливает значение ключа "a" равным 10, если ключ отсутствует, и возвращает его значение.  
В итоге: 0 + 10 + 10 = 20

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#19+

In [11]:
d = {"id": 1, "person": {"name": "Vasya", "age": 18}}
d1 = d.copy()
d1["person"]["age"] += 1
d2 = d
d2["person"]["age"] += 1
print(d["person"]["age"])

20


In [ ]:
18
19
20
TypeError
AttributeError

Здесь создается поверхностная копия, поэтому вложенный словарь не копируется, лишь его ссылка, и все изменения в копиях отражаются на вложенном словаре.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#20+

In [ ]:
Как вывести список установленных библиотек Python?

In [ ]:
pip show
pip search
pip check
pip list
pip completion
pip cache

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#21+  5 февраля 2021

In [12]:
"{0:b}{1:#o}".format(3, 8)

'110o10'

In [ ]:
'1110'
'11o10'  
'110o10'  #
'0o1011'
'110b1000'
'30o10'

Форматирование строки: по первому индексу ставится 3 в двоичном виде, по второму - число 8 в восьмеричном с префиксом 0o (из-за #)

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
/////////////////////////

In [ ]:
#22+

In [1]:
def f(x, y):
    return x ** y
print(f.__call__(3, 2) + f(2, 3))

17


In [ ]:
8
9
10
16
17  #
27
AttributeError

Код определяет функцию f(x, y) для возведения в степень. Вызывает функцию дважды с разными аргументами и суммирует результаты.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#23+

In [2]:
sum(divmod(16,5), 5)

9

In [ ]:
4
5
8
9  #
26

divmod(16, 5) возвращает (3, 1), потому что 16 делится на 5 с остатком 1.
sum((3, 1), 5) = 3 + 1 + 5 = 9.

In [ ]:
#24+

In [4]:
def f(*, name):
    print(len(name), end=" ")

try:
    f(name="vasya")
    f("sergey")
except:
    f(name="oleg")

5 4 

In [ ]:
4
5 6
5 6 4
6 4
5 4 #
TypeError

Сигнатура функции f подразумевает использование именованного аргумента 'name', без позиционных. Поэтому f("sergey") кидает исключение.

In [ ]:
#25+

In [5]:
class A: pass
class B:
    def __init__(self):
        x = super()
        print(x is A, x is B)

b = B()

False False


True True
True False
False True
False False #

In [12]:
class A: pass
class B:
    def __init__(self):
        x = super()
        print(x)
        print(type(x))
        print(isinstance(x, A), isinstance(x, B))
        print(x is A, x is B)

b = B()

<super: <class 'B'>, <B object>>
<class 'super'>
False False
False False


x - это временный объект класса В, который является экземпляром класса super. Поэтому х не является экземпляром ни B ни A.

In [ ]:
#26   29 января 2021

In [13]:
5 >> 1 << 1

4

In [ ]:
0
1
4  #
5
511

Сперва происходит сдвиг (в бинарном представлении) на один разряд вправо, затем влево. Сдвиг на один разряд вправо - это целочисленное деление на 2, влево - умножение на 2.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
...//////////////////

In [ ]:
#27+

In [1]:
def counter(func):
    def oncall(*args): 
        oncall.calls += 1
        return func(*args) + oncall.calls
    oncall.calls = 0
    return oncall
class C:
    @counter
    def square(self, a): 
        return a ** 2
x = C()
print(x.square(2) + x.square(2))

11


In [ ]:
7
8
10
11  #
12

counter - декоратор, который добавляет счетчик вызовов к функции.
При 1-м вызове счетчик равен 1, при 2-м равен 2.;   2^2+1 + 2^2+2 = 5 + 6 = 11


In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#28+

In [2]:
def decorator(cls):
    class Proxy:
        def __init__ (self, *args): 
            self.wrapped = cls(*args)
        def __getattr__(self, name): 
            return 1 if name == 'x' else getattr(self.wrapped, name)
    return Proxy

@decorator
class S:
    def __init__(self, x):
        self.x = x
    def square(self): 
        return self.x ** 2 
s = S(10) 
print(s.square() + s.x)

101


In [ ]:
1
10
20
100
101 #
110
200

Декоратор создает прокси-объект, который при обращении к аргументу x возвращает 1, другие аргументы делегирует объекту S. Поэтому: s.square() = 10^2 = 100;
s.x = 1; 100 + 1 = 101

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#29+

In [3]:
class counter:
    def __init__(self, func): 
        self.calls = 0
        self.func = func
        
    def __call__(self, *args): 
        self.calls += 1
        return self.func(*args), self.calls
    
@counter 
def square(a): 
    return a ** 2

print(square(2)[0] + square(3)[0] + square(4)[1])

16


In [ ]:
3
6
15
16   #
29


1-й вызов square(2), функция возвращает кортеж (2 ^ 2, 1) = (4, 1); 
2-й - (3 ^ 2, 2) = (9, 2);
3-й - (4 ^ 2, 3) = (16, 3);
square(2)[0] + square(3)[0] + square(4)[1] = 4 + 9 + 3 = 16

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#30+

In [4]:
(0 or 8 != 11 or 0) + (0 and 8 != 11 and 0)

1

In [ ]:
True
False
0
1  #
2

!= имеет более высокий приоритет, чем or и and. А and - более высокий, чем or.
(0 or 8 != 11 or 0) = True;
(0 and 8!= 1 and 0) = False;
при сложении True=1; False=0 => 1 + 0 = 1

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#31 + 22 января 21

In [5]:
import random
random.random() < random.randint(1, 10)

True

In [6]:
True  #
False
AttributeError
TypeError
Неопределено

True

Функция random() из модуля random возвращает любое число x такое, что 0 <= x < 1; а функция randint(1, 10) - целое число от 1 до 10. Поэтому второй вызов всегда будет больше первого

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
////////////////////////////////////

In [ ]:
#32+

In [1]:
class A:
    count = 0
    @classmethod
    def inc(cls):
        cls.count += 1 
    def __init__ (self):
        self.inc() 
        
class B(A):
    count = 0
    def __init__(self): 
        A.__init__(self)
        
class C(A): 
    count = 0
    
x = A()  
y1, y2 = B(), B() 
z1, z2, z3 = C(), C(), C()
print(x.count, y1.count, z1.count)

1 2 3


In [ ]:
1 2 3  #
1 3 7
1 3 0
1 2 0
1 0 0
1 3 3

Классы B и C наследуются от A и имеют атрибут count, который увеличивается при создании объекта. При выводе значений счетчиков x.count, y1.count и z1.count, будет выведено "1 2 3", что соответствует количеству созданных объектов каждого класса. И хранится в переменной count соответствующего класса.

In [ ]:
#33+

In [3]:
class A:
    count = 0 
    def __init__(self) :
        self.__class__.count += 1
  
class B(A):
    pass
                  
class C(A):
    pass 

x, y, z = B(), A(), C()
print(A.count, B.count, C.count)

1 1 2


In [ ]:
1 1 1
1 1 2   #
1 2 2
2 2 2 
1 2 3

При создании экземпляров классов A, B, C вызывается конструктор класса A. Изначально count нет в B,C, поэтому берется значение из A и новое записывается в текущий класс B или C. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#34+

In [5]:
class A:
    count = 0 
    def __init__(self):
        A.count += 1
    def print_count():
        print(A.count)  
    print_count = staticmethod(print_count)
    
class B(A): pass

x, y, z = B(), A(), B() 
B.print_count()

3


In [ ]:
1
2
3   #
4
AttributeError

Каждый раз при создании экземпляра A или B (наследуется от A) увеличивается count (который есть переменная класса A) на 1. Создано всего 3 экземпляра.

Код создает два класса, A и B, где B наследуется от A. Атрибут count увеличивается на 1 каждый раз при создании объекта класса A или его подкласса. В результате, при вызове метода B.print_count(), который является статическим методом, будет выведено число 3, соответствующее количеству созданных объектов.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#35

In [6]:
class A:
    count = 0
    def __init__(self):
        A.count = A.count + 1
    def get(self):
        return A.count
x, y, z = A(), A(), A()
print(x.get(), A().__class__.get(A()), z.__class__.get(y))

3 5 5


In [ ]:
3 3 3
3 4 5
3 5 3
3 5 5  #
3 5 6

При создании экземпляра A переменная count этого класса увеличивается на 1. Создается 3 экземпляра - x, y, z. При вызове x.get только они и есть, но во втором аргументе print создается еще два экземпляра A, уже будет 5. 

При создании экземпляров x, y, z класса A переменная класса count увеличивается на 1. При вызове x.get только они и есть, но во втором аргументе print создается еще два экземпляра A, уже будет 5. 

In [ ]:
/////////////

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#36+

In [1]:
class X: pass
class A(X): pass 
class B(X): pass 
class D(A, B): pass
print([cls.__name__ for cls in D.__mro__])

['D', 'A', 'B', 'X', 'object']


In [ ]:
['D', 'A', 'B', 'X']
['D', 'A', 'B', 'X', 'object']    #
['D', 'A', 'X', 'B', 'object']
['D', 'A', 'X', 'B']

MRO определяет порядок, в котором осуществляется поиск атрибутов и методов при наследовании. В Python используется алгоритм C3 линеаризации для определения MRO.
В итоге: D -> A -> B -> X -> object

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#37+

In [3]:
x = 9
y = 2
print(divmod(x, y) == (x // y, x % y), divmod(x, y) is (x // y, x % y))

True False


In [ ]:
True True
True False  #
False True
False False

divmod(x, y) возвращает кортеж с результатом целочисленного деления и остатком от деления. 
divmod(x, y) == (x // y, x % y) равно True, так как значения совпадают. Однако, divmod(x, y) is (x // y, x % y) равно False, потому что это разные объекты в памяти.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#38+

In [4]:
class C: pass
class D (C): __slots__ = ['a']
X = D() 
X.a = 1
class A: __slots__ = ['b']
class B (A): __slots__ = ['b']
Y = B() 
Y.b = 1
print(hasattr(X, '__dict__'), hasattr(Y, '__dict__'))

True False


In [ ]:
True True
True False  #
False True
False False

При указании _slots_ атрибут _dict_ отсутствует. В первом случае он берется из класса C, так как там нет _slots_

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#39+

In [5]:
sum([10, 20, 30, 40], 10) - sum([], 10)

100

In [ ]:
80 
90
100 #
110
120


Функция sum суммирует элементы из списка в первом аргументе, имея начальное значение суммы из второго аргумента. Первая сумма даст 110, а вторая - 10 (т.к. пустой список).

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#40+

In [6]:
class X: pass
class Y: pass
class A(X): pass 
class B(Y): pass 
class D(A, B): pass
print([cls.__name__ for cls in D.__mro__])

['D', 'A', 'X', 'B', 'Y', 'object']


In [ ]:
['D', 'A', 'X', 'B', 'Y', 'object']  #
['D', 'A', 'B', 'X', 'Y', 'object'] 
['D', 'A', 'X', 'B', 'Y']
['D', 'A', 'B', 'X', 'Y'] 
['D', 'A', 'X', 'B', 'Y']
['D', 'A',  'object', 'B', 'X']

MRO для класса D будет следующим: D -> A -> X -> B -> Y -> object 
Алгоритм MRO идет вглубь до общего предка (не включая его), затем переходит к следующему на том же уровне. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#41+

In [7]:
sum((round(1.5), round(2.5), round(3.5), round(4.5)), 3)

15

In [ ]:
17
16
15  #
14
13
12
10
TypeError

round() округляет число до ближайшего целого числа (четного, если равноудалены). sum((2, 2, 4, 4), 3) = 2 + 2 + 4 + 4 + 3 = 15 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#42 + 7 янв 2021

In [8]:
sum((pow(3, 3, 2), pow(2, 3, 7)), 1)

3

In [ ]:
1
2
3   #
35
36
TypeError

pow() принимает три аргумента: основание, показатель степени и модуль
pow(a, b, c) = a ^ b % c

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
..................

In [ ]:
#43+

In [ ]:
Дан код:

In [1]:
class C: pass
class D (C): __slots__ = ['a']
X = D() 
X.a = 1
print(hasattr(X, '__dict__'))

True


In [ ]:
Вывод: True

In [ ]:
Что нужно написать в классе С вместо pass, чтобы вывод был False?

In [ ]:
a = 1
del __dict__
del self.__dict__
__slots__ = ['a']     #
def __init__(self): del self.__dict__

Атрибут dict берется из класса C, но когда устанавливаем у него slots, то dict он уже не имеет, поэтому и у наследника не будет

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#44+

In [4]:
print(bin(2**2) == bin(2**3 >> 1),  bin(2**2) is bin(2**3 >> 1))

True False


In [ ]:
True True
True False  #
False True
False False

bin(2^2) даст бинарное представление числа 4, то есть '0b100';
bin(2^3 >> 1) даст '0b100'(8 сдвигаем на разряд вправо);
Оператор == проверяет, равны ли значения, а оператор is проверяет, один ли объект

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#45+

In [5]:
None or False and True

False

In [ ]:
None
False  #
True
TypeError

In [ ]:
and имеет более высокий приоритет, чем or;
сначала выполняется операция False and True, даст False;
затем None or False, даст False.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#46+

In [5]:
x = False or None and True
print(x)

None


In [ ]:
None  #
False  
True
TypeError

In [ ]:
and имеет более высокий приоритет, чем or;
сначала выполняется операция None and True, даст None;
False or None даст None.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#47+

Целое число "x" можно проверить на нечетность с помощью остатка от деления по модулю
cледующим образом: `x % 2`. Какой эквивалент данному выражению можно использовать в логических условиях?

In [ ]:
x >> 1
x++
x ** x - 1
x & 1  #
x | 1
x @ 2

x % 2 будет истинным, когда остаток от деления равен 1 (число нечетное). x & 1 - побитовое 'И' с числом 1, оставит только младший разряд x, если он 1 (x нечетное), то итог 1, иначе 0.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#48+

In [6]:
True + ~False

0

In [ ]:
True
False
0    #
1
None

True=1, False=0
~ - эта операция инвертирует все биты числа x, что эквивалентно выражению -(x + 1);  
~False = -(0 + 1) = -1;
True + ~False = 1 + (-1) = 0


In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
//////////////////////////

In [ ]:
#49+

In [1]:
"python" * 0 is '' * 10

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-1-b1850947398d>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  "python" * 0 is '' * 10


True

In [ ]:
0
python
True  #
False

"python" * 0, умножает строку "python" на 0, что дает пустую строку;
'' * 10, умножает пустую строку ('') на 10, что также дает пустую строку. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#50+

In [2]:
import numpy as np
A = np.random.randint(1, 100, size=(5, 5))
B = A.copy()
B[:, [0, -1]] = B[:, [-1, 0]]
d = lambda x: round(np.linalg.det(x))
print(d(A) + d(B))

0


In [ ]:
0.0  #
1.0
7.0
100.0
None
nan

Перестановка двух столбцов матрицы приводит к изменению знака определителя, но неизменности его значения по модулю, поэтому в сумме получаем ноль

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#51+

In [4]:
print("python".zfill(10))

0000python


In [5]:
0000000000python
python0000000000
0000000000python0000000000
0000python   #
python0000
0000python0000

SyntaxError: invalid syntax (<ipython-input-5-4631731f9913>, line 1)

Метод zfill() заполняет нулями слева, чтобы длина строки стала равной 10

Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#52+

In [6]:
"I have 10 cars".isalnum()

False

In [ ]:
I have 10 cars
True
False   #
None
AttributeError

isalnum вернет True, если в строке только цифры и буквенные символы. В нашем случае есть еще пробелы

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#53+

In [7]:
-True % 13 + True % 13

13

In [ ]:
True
False
0
1
13   #
SyntaxError

In [ ]:
-1 % 13 = 12; 1 % 13 = 1; 12 + 1 = 13

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#54+

Как перезагрузить ранее импортированный модуль somemodule, если его код был изменен (Python 3)?

In [ ]:
import somemodule
import importlib; importlib.reload(somemodule)  #
somemodule.reload()
somemodule.reimport()
import somemodule with reload
reimport somemodule

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#55+

In [9]:
from math import log
from functools import reduce
f = lambda acc, x: x * acc
gen = (abs(log(i / 10)) for i in range(1, 1000))
print(int(reduce(f, gen, 1)))

0


In [ ]:
-1
0  #
1
10
17844
None
ValueError

результатом будет произведение чисел вида log(i / 10), где 1 <= i < 1000. Поскольку при i = 10 число будет log(10 / 10) = log(1) = 0, то и произведение будет 0

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#56+

In [10]:
from random import randint
num = randint(10**8, 10**20)
s = bin(num)[2:].replace('0', '\n').replace('1', '\t')
print(s.isspace())

True


In [ ]:
0
1
True   #
False
\n
\t
TypeError

Cлучайное число преобразуется в двоичный вид, причем 0 и 1 заменяются на \n и \t. isspace вернет True, так как получаются только пробельные символы

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
следующая задача - 14 дек 20

In [ ]:
..................

In [ ]:
#57+

In [1]:
class MyList(list):
    def __iter__(self):
        return iter(self*2)
m = MyList([1, 2, 3])
print(list(m))

[1, 2, 3, 1, 2, 3]


In [ ]:
[]
[1, 2, 3]
[1, 2, 3, 1, 2, 3]   #
TypeError
IndexError

Этот код создает подкласс списка, который при итерации возвращает итератор от удвоенного списка.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#58+

In [ ]:
В каких случаях в Python 3 ответом будет число типа int?

In [ ]:
8.0 - 3
4 / 2
7 // 2  #
3 / 2
4 + 1.0
4.5 % 3

Сложение и вычитание типов int и float, а также деление даст float. А целочисленное деление дает int.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#59+

In [2]:
(2 << 2) + (20 >> 2)

13

In [ ]:
2
8
11
13  #
14
232
True

Побитовый сдвиг влево на два разряда равносилен умножению на 4. А вправо - целочисленному делению на 4.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#60+

In [3]:
f = lambda x: isinstance(x, int)
print(f(1), f(1.0), f(True), f(1j))

True False True False


In [ ]:
True True True True
True True False True
True False True False  #
True True False False
True False False False

Лямбда-функция f в этом коде проверяет, является ли аргумент целым числом. f(1) и f(True) возвращают True, так как 1 и True считаются целыми числами в Python. Однако f(1.0) и f(1j) возвращают False, так как 1.0 - это число с плавающей запятой, а 1j - комплексное число.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#61+

In [4]:
g = (str(i**2) for i in range(1, 4))
print("".join(g) + "".join(g))

149


In [ ]:
14
116
123
1234
149    #
149149
14916
1491614916

Первый вызов "".join(g) вернет строку, состоящую из квадратов чисел от 1 до 3. Поскольку генератор исчерпан, второй вызов "".join(g) не вернет ничего.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#62+

In [5]:
class D:
    __slots__ = ["a", "__dict__"]
    def __init__(self):
        self.b = 2
d = D()
d.a = 1
d.c = 3
print(sorted(d.__dict__.values()))

[2, 3]


In [ ]:
[1, 2, 3]
[1, 2]
[2, 3]   #
[1, 3]
[1]
[2]
AttributeError

__dict__  включен в __slots__, что позволяет экземплярам класса D иметь динамические атрибуты, помимо тех, что определены в __slots__. Aтрибут a находится в __slots__, он не будет включен в d.__dict__

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#63+

In [6]:
6 + ~6

-1

In [ ]:
-1  #
0
1
6
12
SyntaxError

~ - эта операция инвертирует все биты числа x, что эквивалентно выражению -(x + 1);
x + ~x = x + (- (x + 1)) = x - x - 1 = -1

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#64+

In [ ]:
class D:
    __slots__ = ['a', 'b']
d = D()
d.a = 1
f = lambda attr: getattr(d, attr, '*')
print(f('a'), f('b'), f('__dict__'))

In [ ]:
1 1 1
1 1 *
1 * *   #
* * *
* 1 1
* * 1

Атрибут b не выводится, так как он не был установлен, а _dict_ отсутствует из-за определения атрибута _slots_

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#65+

In [7]:
def invertdict(D):
    def keysof(V):
        return sorted(K for K in D.keys() if D[K] == V)
    return {V: keysof(V) for V in set(D.values())}
D = {'x': 'a', 'y': 'b', 'z': 'a'}
print(invertdict(D))

{'b': ['y'], 'a': ['x', 'z']}


In [ ]:
{'a':'x', 'b':'y', 'a':'z'}
{'b':['y'], 'a':['x', 'z']}   #
{'y':['b'], 'x, z':['a']}
{'a':['y'], 'b':['x', 'z']}
AttributeErrror

invertdict принимает словарь и возвращает новый, где ключи и значения исходного словаря меняются местами. Если у одного значения в исходном словаре было несколько ключей, они становятся списком

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#66+

In [8]:
class MyList(list):
    def __getitem__(self, index):
        return super().__getitem__(index) * 2
m = MyList([1, 2])
print([m[i] + x for i, x in enumerate(m)])

[3, 6]


In [ ]:
[1, 2]
[1, 2, 1, 2]
[2, 4]
[3, 6]  #
TypeError
IndexError

Этот код создает подкласс списка, который удваивает каждый элемент при обращении к нему по индексу. Создается экземпляр этого класса с элементами 1 и 2. Затем выполняется генератор списка, который суммирует удвоенное значение каждого элемента с его исходным значением, в результате получается [3, 6].

MyList - подкласс list, который при обращении к элементу по индексу возвращает удвоенное значение элемента списка. Но при итерации удвоения не происходит.  1*2+1=3; 2*2+2=6

In [ ]:
3 dec 20

In [ ]:
...................

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#67+

In [1]:
class A: pass
class B(A): pass 
class C1(A): pass 
class C2: pass
class D1(B, C1): pass
class D2(B, C2): pass

X = list(D1.__mro__)
Y = list(D2.__mro__)
print(X[3] is Y[2])

True


In [ ]:
True  #
False
TypeError
AttributeError

MRO для классов D1 и D2:
D1: D1, B, C1, A, object;
D2: D2, B, A, C2, object;
В данном случае, оба класса D1 и D2 имеют класс A в своём MRO. Поэтому код X[3] is Y[2] выведет True.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#68+

In [4]:
int(2) is 2 * True

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-4-2f91c90e43b7>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  int(2) is 2 * True


True

In [ ]:
0
1
2
True   #
False
TypeError

int(2) возвращает число 2. 2 * True также даёт 2, потому что True интерпретируется как 1 в математических вычислениях. Таким образом, int(2) is 2 * True вернёт True.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#69+

In [3]:
class A: attr = 1  
class B(A): pass
class C(B): pass
class D(A): attr = 2
class E(C, D): attr = C.attr  
x = E()
print(x.attr)

1


In [ ]:
1    #
2
None
AttributeError

У класса E MRO такой: E-C-B-D-A-object, но у E attr берется из C, а там MRO будет C-B-A-object, то есть attr будет браться не из D, а из A.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#70+

In [8]:
a = type([1, 2, 3]) == type(list)
b = [1, 2, 3].__class__ == list.__class__
print(a, b)

False False


In [ ]:
True True  
True False 
False True 
False False   #
TypeError
AttributeError

type([1, 2, 3]) возвращает <class 'list'>, а type(list) возвращает <class 'type'>, что делает a равным False. Атрибут __class__ указывает на класс объекта, но list.__class__ возвращает <class 'type'>, поэтому b также равно False. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#71+

In [9]:
class A: attr = 1  
class B(A): pass     
class С(A): attr = 2
class D(B, С): pass   
x = D()
print(x.attr)

2


In [10]:
D.__mro__

(__main__.D, __main__.B, __main__.С, __main__.A, object)

In [ ]:
1
2  #
None
AttributeError

MRO определяет иерархию поиска атрибутов. Здесь, иерархия это D -> B -> C -> A -> object. Поскольку attr не определен в D и B, Python ищет его в классе C, где attr равен 2

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#72+

In [11]:
isinstance(type, object) + isinstance(object, type) + (type is object)

2

In [ ]:
0
1
2  #
3
True
False
TypeError

object - это instance класса type, но type наследуется от object, при этом type - instance самого type, а значит, и object тоже. Поэтому первые два слагаемых дадут True.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#73+

In [12]:
class С: pass 
c = С() 
a = type(c) == c.__class__
b = type(type(c)) is c.__class__.__class__
print(a, b)

True True


In [ ]:
True True   #
True False 
False True 
False False 

type(c) и c.__class__ возвращают класс объекта c, что делает a равным True. type(type(c)) и c.__class__.__class__ возвращают класс type, так как тип класса C - это type, что делает b также равным True

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#74+

In [13]:
f = type
print(f(f(f(f(f(None))))) is f )

True


In [ ]:
True  #
False
None
Будет ошибка

type(None) -> NoneType;
type(type(None)) -> type;
type(type) -> type;
Поэтому исходное выражение слева будет равно type, что является тем же объектом, что и f

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#75+

In [18]:
class A:
    x = 'python'
    def __getitem__(self, i):
        return getattr(self.x, '__getitem__')(i) * 2
    def __getattr__(self, attr):
        return getattr(self.x, attr)
a = A()
print(a[0] + a.upper()[1:])

ppYTHON


PYTHON
pYTTON
ppython
ppYTHON    #
PPYTHON

При обращении по индексу возвращается удвоенный символ соответствующей позиции в строке x (a[0] -> pp), а остальные методы делегируются объекту x (метод upper)

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#76+

In [20]:
from functools import reduce
print(reduce(lambda acc, x: x * acc, [1,2,3,4], 1))

24


In [ ]:
0
1
10
24   #
TypeError

reduce производит свертку - на каждой итерации берет новое значение из списка и аккумулируемое значение и возвращает их произведение. Начальное значение = 1. В итоге - произведение всех чисел списка

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
23 nov 20

In [ ]:
....................

In [ ]:
#77+

In [1]:
class A:
    def __getitem__(self, i):
        return i
a = A()
a.__getitem__ = lambda i: i**2

print(a[4])

4


In [ ]:
4   #
8
16
None
IndexError
TypeError

a[4] - код обращается к методу __getitem__ класса A и возвращает переданный индекс i.  Присвоение a.__getitem__ не используется.
https://docs.python.org/3/reference/datamodel.html#special-lookup

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#78+

In [2]:
class A:
    def __init__(self, x):
        self.x = x
    def __getattribute__(self, name):
        if name == '__add__':
            self.x *= 10
        return object.__getattribute__(self, name)
    def __add__(self, other):
        return self.x + other.x

a1 = A(2)
a2 = A(3) 
print(a1 + a2, a1.__add__(a2))

5 23


In [ ]:
5 5
23 5
5 23   #
23 23
NameError
RecursionError

При a1 + a2 (неявный вызов add) метод getattribute не вызывается для add, а при a1.add(a2) он будет вызван.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#79+

In [3]:
a = 1 * 1
b = 1 / 1
print(a == 1, b == 1, a is 1, b is 1)

True True True False


<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-3-6c639b4603d9>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a == 1, b == 1, a is 1, b is 1)
<ipython-input-3-6c639b4603d9>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a == 1, b == 1, a is 1, b is 1)


In [ ]:
True True True True
True True True False  #
True True False False
True False False False
False False False False

1 * 1 дает 1 - тип int, 1 /1 дает 1.0 - тип float, сравнение 1 == 1.0 дает True, а 1 is 1.0 - False, так как 1 и 1.0 - это разные объекты

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#80+

In [4]:
class MyList(list):
    def __getitem__(self, index):
        if type(index) is slice:
            index = slice(index.start - 1, index.stop - 1, index.step)
        elif type(index) is int:
            index -= 1
        return list.__getitem__(self, index)

l = MyList(["one", "two", "three", "four", "five", "six"])

print(l[1], l[-1], l[0], l[2:4])

one five six ['two', 'three']


In [ ]:
two six one ['three', 'four']
one six None ['two', 'three']
one five six ['two', 'three'] #
one five six ['three', 'four']
one five six None
IndexError
TypeError
AttributeError

При обращении по индексу происходит уменьшение индекса на 1 и получение по этому новому индексу элемента из списка. Аналогично со срезами, там уменьшаются на 1 обе границы

# начиная с 18 марта 2021

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#81

In [5]:
class A:
    __x = 1
    def f(self):
        return "f from A"
    
    def g(self):
        return "g from A"

class B:
    __x = 2
    def f(self):
        return "f from B"
    
    def g(self):
        return "g from B"

class C(A, B):
    f = B.f
    
c = C()
print(c.f(), c.g(), c._A__x, c._B__x)

f from B g from A 1 2


In [ ]:
f from A g from A 1 2
f from B g from B 1 2 
f from A g from B 1 2 
f from A g from B 2 1 
f from B g from A 1 1
f from B g from A 2 2
f from B g from A 1 2  #
f from B g from A 2 1

c.f() вызывает f из B, так как в C есть метод f, которые копируется из B, а метода g нет для c.g(), поэтому берется по цепочке MRO из A. Для доступа к переменным с двумя подчеркиваниями в начале надо использовать имя класса.

In [ ]:
след 19 марта 2021

In [ ]:
......................

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#82+

In [1]:
def intersect(*seqs):
    if len(seqs) > 2:
        return intersect(seqs[0], intersect(*seqs[1:]))
    seq1, seq2 = seqs[0], seqs[1]
    res = []
    for x in seq1:
        if x in seq2:
            res.append(x)    
    return res

x = intersect([1, 2, "a", "b"], (1, 4, "b"), {1, "b", "c"}) 
print(x)

[1, 'b']


In [ ]:
[1, 2, 4, 'a', 'b', 'c']
[1, 'b', 'c']
[1, 'b']  #
[1]
([1, 2, 'a', 'b'],  [1, 'b'])
IndexError

Код находит общие элементы между несколькими последовательностями. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#83+

In [2]:
def f(n):
    return 0 if n == 0 else 2**n + f(n-1)
print(f(3))

14


In [ ]:
0
8
12
13
14   #
16

In [ ]:
Рекурсивно вызывается f, равносильно f(3) = 2^3 + 2^2 +2^1

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#84+

In [3]:
def f():
    x = 1
    y = 1
    def g():
        nonlocal x
        x, y = 2, 2
    g()
    print(x, y)

f()

2 1


In [ ]:
1 1
1 2
2 1   #
2 2
NameError

x берется из области видимости f из-за nonlocal, а y - локальный в g. Поэтому x изменится в f, а y - нет

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#85+

In [4]:
try:
    my_x = 1
    raise Exception('исключение') #1
except Exception as my_err:
    print(my_err)                 #2
    my_y = 2
print(my_x)                       #3
print(my_y)                       #4
print(my_err)                     #5

исключение
1
2


NameError: name 'my_err' is not defined

In [ ]:
Какая из строчек в данном коде вызовет неперехваченное исключение:

In [ ]:
1
2
3
4
5  #

my_err определена только для блока except, но во внешней области видимости ее нет

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#86+

In [5]:
x = 1
def f1():
    return x
def f2():
    global x
    x = 2
    return x
def f3():
    global x
    return x
print(f1(), f2(), f3(), f1())

1 2 2 2


In [ ]:
1 2 1 1
1 2 2 1
1 2 2 2   #
1 2 1 2
2 2 2 2

Функции f1(), f2(), и f3() работают с глобальной переменной x. Первоначальное значение x - 1, f1() возвращает его, f2() изменяет x на 2 и возвращает, f3() и f1() также возвращают это значение. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#87+

In [ ]:
Даны два модуля testmod.py и runmod.py
#testmod.py
x = 0
def f1():
    x = 10
def f2():
    global x
    x += 1   
def f3():
    import testmod
    testmod.x += 1
def f4():
    import sys
    sys.modules["testmod"].x += 1

#runmod.py
import testmod as t
t.f1();t.f2();t.f3();t.f4()
print(t.x)

In [ ]:
Точкой входа в программу является модуль runmod.py.
Какой будет вывод?

In [ ]:
0
1
2
3  #
10
11
12
13

f1 не меняет x, так как присвоение в локальной области видимости. Остальные функции меняют разными способами. Повторный импорт модуля в f3 приведет к использованию старого объекта модуля

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#88+

In [6]:
def maker(n):
    s = 0
    def g(x=n):
        nonlocal s
        s += x
        return s
    return lambda x: s + x + g()
f = maker(2)
print(f(3), f(3))

5 9


In [ ]:
3 5
5 5
7 7
5 7
5 9     #
7 9
9 9

Функция g увеличивает s на n из области видимости f и возвращает его. В первый вызов f: s = 0, поэтому вернет 0 + 3 + (0 + 2). Во-второй вызов: 2 + 3 + (2 + 2) = 9

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#89+

In [7]:
f = lambda x, f=lambda x: x**2:  f(x)
print(f(5), f(5, f))

25 25


In [ ]:
5 5
5 (5, 5)
5 25
5 125
5 (25,  25)
25 25        #
25 125
125 125
5 (125, 125)

Функция f принимает x и f, которое по умолчанию возводит в квадрат.  f(5) - не передали второй аргумент, значит вернет 5 ^ 2 = 25. f(5, f) вернет f(5) = 25, так как суть f - применить второй аргумент (функцию) к первому.

f принимает x и функцию, по умолчанию x ^ 2.  f(5) - не передали второй аргумент, значит вернет 5 ^ 2 = 25. f(5, f) вернет f(5) = 25, так как суть f - применить второй аргумент (функцию) к первому

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#90+

In [8]:
def maker(n, h=lambda: 3):
    return lambda f=h: f()**n, lambda f=h: n**f()
f, g = maker(2)
r = f(g) + g(f)
print(r)

576


In [ ]:
5
17
31
72
73
128
576   #
19699

In [ ]:
n = 2; ^ - степень;
f(g) = g() ^ n = (n^3) ** 2 = (2^3)^2 = 64;
g(f) = n^f() = n ^ (3 ^ n) = 2 ^ (3 ^ 2) = 2 ^ 9  = 512;
64 + 512 = 576

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
.........................................

In [ ]:
#91+

In [9]:
funcs = [lambda x: x**i for i in range(2, 4)]
print(funcs[0](5))

125


In [ ]:
5
25
[25]
125        #
[25, 125]
625

Код создает список из двух лямбда-функций, которые возводят x в степень i, причем i берется извне функции и в момент вызова i=3(замыкание). funcs[0](5) вернет 5^3 = 125.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#92+

In [10]:
def f():
    def g():
        nonlocal x
        x = 2
    g()
    print(x)
        
f()

SyntaxError: no binding for nonlocal 'x' found (<ipython-input-10-3cfbaa501261>, line 3)

In [ ]:
2
None
SyntaxError   #
NameError

Код определяет внутреннюю функцию g(), которая пытается изменить не глобальную, а внешнюю переменную x с помощью оператора nonlocal. Однако, в данном контексте переменная x не определена в области видимости функции f(). Это приведет к ошибке SyntaxError

Код определяет внутреннюю функцию g, она меняет внешнюю переменную x (nonlocal). Однако, в данном контексте переменная x не определена в области видимости функции f. Это приведет к ошибке SyntaxError

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#93+

In [11]:
def f():
    def g():
        global x
        x = 2
    g()
    print(x)
        
f()

2


In [ ]:
2     #
None
SyntaxError
NameError

Функция g() использует оператор global для работы с переменной x, устанавливая ее значение равным 2. При этом неважно, была ли определена эта переменная в глобальном пространстве имен ранее.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#94+

In [2]:
def f(name="", value=0):
    import sys
    func_name = sys._getframe(0).f_code.co_name
    func = sys._getframe(1).f_locals[func_name]
    setattr(func, name, value)
    return sum(func.__dict__.values())

print(f("x", 1), f("y", 2), f())

1 3 3


In [ ]:
1 1 1
1 2 2
1 2 3
1 3 3      #
1 2 None
3 3 3

Здесь через sys_getframe получаем имя текущей функции, а также ссылку на нее из предыдущего стэка вызовов, после чего присваиваем ей как объект переданные атрибут и значение

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#95+

In [13]:
a = b, c = [1, 2]
a[0] = 10
print(b, c)

1 2


In [ ]:
1 2   #
10 2
10 1 2
None 2
TypeError

Это равносильно
a = [1, 2];
b, c = [1, 2];
поэтому изменения в a не отразятся на b и c

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
след 9 апр 21

In [ ]:
#96+

In [4]:
def f():
    x = 1
    def g():
        x += 1
    g()
    print(x)
print(f())

UnboundLocalError: local variable 'x' referenced before assignment

In [6]:
1
2
None
SyntaxError
UnboundLocalError  #

Функция g пытается увеличить x на 1, но Python рассматривает x как локальную переменную для g, так как есть присваивание, и это приводит к ошибке UnboundLocalError из того, что x не определена в g.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#97+

In [7]:
def func(а, b):
    а = 2
    b = b[:] 
    b[0] = 10
    
a, b = [0], [1]
func(a, b)
print(a, b)

[0] [1]


In [ ]:
[0][10]
0 10
[0][1]   #
0 1
[2][10]
2 10
[2][1]
2 1

Переменные a и b внутри функции func являются новыми локальными переменными, которые не связаны с внешними переменными a и b. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#98+

In [8]:
def func(a, b):
    а = 2
    b[0] = 10
x = 1
y = 1, 2
func(x, y)
print(x, y)

TypeError: 'tuple' object does not support item assignment

In [ ]:
1(1,2)
2(1,2)
1(10,2)
2(10,2)
1 10
2 10
TypeError   #

Кортежи в Python неизменяемы, поэтому операция b[0] = 10 вызовет ошибку.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#99+

In [ ]:
Дан код

In [10]:
def f(a, b, c, d):
    print(a, b, c, d)

In [ ]:
Какой способ передачи аргументов при вызове функции вызовет ошибку?

In [ ]:
f(1, b=2, *(3,), **{"d":4})   #
f(1, c=2, *(2,), **{"d":4}) 
f(c=3, b=2, a=1, **{"d":4}) 
f(*(1,2), **{"c":3, "d":4})
f(1,*(2,3), **{"d":4})
f(1, 2, 3, *(4,))

Первый вариант не подходит, так как возникает неоднозначность относительно аргумента b, он явно присваивается и в тоже время берется из *(3,)

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#100+

In [ ]:
Какое объявление функции не вызовет ошибку во время создания функции?

In [ ]:
def f(a, b=1, *c=(2,), **d): pass
def f(a, b, **c, d): pass
def f(a=1, b=2, c): pass
def f(a=1, *b, c): pass    #
def f(a=1, **b, c): pass
def f(**a, b=1, c): pass

https://towardsdatascience.com/10-examples-to-master-args-and-kwargs-in-python-6f1e8cc30749

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [16]:
#101+

In [12]:
x = 1
def f():
    def g():
        nonlocal x 
        print(x)
        x += 1
    return g

SyntaxError: no binding for nonlocal 'x' found (<ipython-input-12-f07264f1c3d8>, line 4)

In [ ]:
1
2
None
SyntaxError   #
UnboundLocalError
NameError

Код определяет внутреннюю функцию g(), которая пытается изменить не глобальную, а внешнюю переменную x с помощью оператора nonlocal. Однако, в данном контексте переменная x не определена в области видимости функции f(). Это приведет к ошибке SyntaxError

Функция g, меняет не глобальную, а внешнюю переменную x (nonlocal). Однако, в данном контексте переменная x не определена в области видимости функции f. Это приведет к ошибке SyntaxError

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#102+

In [20]:
def f(a, b, c, d, e):
    print(a, b, c, d, e)

f(1, *(3,), c=10, **{"d": 5, "e": 100})

1 3 10 5 100


In [ ]:
1 10 3 5 100
1 3 10 5 100  #
1 3 None 10 5 100
SyntaxError
TypeError
NameError

https://towardsdatascience.com/10-examples-to-master-args-and-kwargs-in-python-6f1e8cc30749

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#103+

In [21]:
def f(s:str = "1") -> int:
    return s * 2
print(f(), isinstance(f(), int))

11 False


In [ ]:
2 True
2 False
11 True
11 False   #

Функция f() возвращает строку, даже если аннотация типа указывает на int. s * 2 дублирует строку, а не умножает число.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#104

In [22]:
def maker(f, args, kwargs):
    return 1 + f(*args, **kwargs)
m1 = maker(lambda a, b: a + b, (5, ), {"b": 2})
m2 = maker(lambda a, b: a * b, [4, 5], {})
print(m1 + m2)

29


In [ ]:
8
21
25
28
29  #

Код использует функцию maker, которая принимает другую функцию и аргументы, применяет их и добавляет 1 к результату. Результаты для m1 и m2 равны 8 и 21, а их сумма равна 29.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
след задача 22 апр 2021

In [ ]:
/////////////////////////////

In [ ]:
#105+

In [1]:
def f(test, *args):
    res = []
    for arg in args:
        if test(arg):
            res.append(arg)
    return sum(res)
data = [-4, 2, -1, 5, -6, 3]
negative = lambda x: x < 0
neg = f(negative, *data)
positive = lambda x: x > 0
pos = f(positive, *data)
print(neg, pos)

-11 10


In [ ]:
-1
0 0
-4 2
[-4, -1, -6][2, 5, 3]
[-11][10]
[10][-11]
-11 10   #
-10 11

Функция f применяет функцию test к каждому элементу args для проверки условия, в этом случае добавляет это значение в список. Вывод сумм всех отрицательных, потом положительных элементов.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#106+

In [4]:
def f(transform, *args):
    res = args[0]
    for arg in args[1:]:
        res = transform(res, arg)
    return res

data = [-4, 2, -1, 5, -6, 3]
func = lambda x, n: x * (-1)**n
print(int(f(func, *data)))

4


In [ ]:
-720
-4
-1
1
4      #
[4, -2, 1, -5, 6, -3]

Этот код применяет функцию func, которая меняет знак числа на основе его позиции. Первое числу из data (-4) умножается на -1 в степени каждое последующее из data. В итоге, -4 * (-1) ^ (2-1+5-6+3) = 4

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#107+

In [3]:
def mintwo(*args):
    tmp = list(args) 
    tmp.sort()
    return tmp[0], tmp[1]
data = [8, -4, 5, -2, 9, 3, -98]
print(*mintwo(*data))

-98 -4


In [ ]:
-102
-98
-2
8 -4
-98 -4  #
9 8
(8, -4)
(-98, -4)
(9, 8)

Этот код определяет функцию mintwo, которая принимает список аргументов, сортирует их и возвращает два наименьших числа. При вызове этой функции для списка data, он выведет два наименьших числа из этого списка, то есть -98 и -4.

Этот код определяет функцию mintwo, которая принимает список аргументов, сортирует их и возвращает два наименьших числа. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#108+

In [5]:
def f(*args):
    result = []
    for x in args[0]: 
        if x in result: 
            continue 
        for word in args[1:]: 
            if x not in word: 
                break 
        else: 
            result.append(x) 
    return ''.join(result)
s1, s2, s3= "message", "massage", "mask"
print(f(s1, s2, s3))

msa


In [ ]:
mesagk
mssa
msa    #
mesag
message
massage
mask
messagemassagemask
пустая строка

Функция f находит общие символы без повторений в переданных строках в порядке появления их в первой строке. Берется первая строка, осуществляется проход по каждому ее символу и проверяется наличие этого символа во всех остальных строках.

Находятся общие символы строк без повторений в порядке появления их в первой строке. Берется первая строка, осуществляется проход по каждому ее символу и проверяется наличие этого символа во всех остальных строках.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#109+

Какой способ проверки того, что переменная a связана с None, является более предпочтительным?

In [ ]:
if not a:
if a == None:
if a is None:   #
if bool(a)==False:
if bool(a) is False:

Оператор is проверяет, что два имени ссылаются на один и тот же объект, что является быстрой операцией, так как приведение типов не требуется

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#110+

In [6]:
def f(*args):
    result = []
    for x in args[0]:  
        for word in args[1:]: 
            if x not in word: 
                break 
        else: 
            result.append(x) 
    return ''.join(result)
s1, s2, s3= "message", "massage", "mask"
print(f(s1, s2, s3))

mssa


In [ ]:
mesagk
mssa   #
msa    
mesag
message
massage
mask
messagemassagemask
пустая строка

Функция f находит общие символы с повторениями в переданных строках в порядке появления их в первой строке. Берется первая строка, осуществляется проход по каждому ее символу и проверяется наличие этого символа во всех остальных строках.

Функция f находит общие символы с повторениями в переданных строках в порядке появления их в первой строке. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#111+

In [7]:
def f(*args):
    res = ""
    l = len("".join(args[:-1]))
    for i, s in enumerate("".join(args)):
        if i > l:
            res += s
    return res
s1, s2, s3= "one", "two", "three"
print(f(s1, s2, s3))

hree


In [ ]:
three
hree   #
two
wo
one
ne
onetwothree
newohree

l = 6 (кол-во символов в строке "onetwo")
В "onetwothree" находятся символы, позиции которых больше 6 и объединяются. То есть hree

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#112+

In [8]:
def mineven(*args):
    res = args[0]
    for arg in args[1: ]:
        if arg < res and arg % 2 == 0:
            res = arg
    return res
data = [3, 2, 1, 0, -1, -2, -3]
mineven(*data)

-2

In [ ]:
-3
-2   #
-1
0
[2, 0, -2]
[-1, -2, -3]
[-3, -2, -1, 0, 1, 2]

Этот код определяет функцию mineven, которая ищет наименьшее четное число среди аргументов. Затем функция применяется к списку data, содержащему числа [3, 2, 1, 0, -1, -2, -3]. Возвращается наименьшее четное число из этого списка, а именно -2.

Этот код определяет функцию mineven, которая ищет наименьшее четное число среди аргументов. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#113+

In [10]:
def f(*args):
    result = []
    for seq in args:
        for x in seq:
            if not x in result:
                result.append(x)
    return ''.join(result)
s1, s2, s3= "message", "massage", "mask"
print(f(s1, s2, s3))

mesagk


In [ ]:
mesagk  #
mssa   
msa    
mesag
message
massage
mask
messagemassagemask
пустая строка

В f осуществляется проход по каждому символу в каждой из переданных строк и добавляется символ в результирующий список только если он еще не присутствует в нем. Затем эти символы объединяются в одну строку.

В f осуществляется проход по каждому символу в каждой из переданных строк и добавляется символ в результирующий список, если его еще там нет. Затем эти символы объединяются в одну строку.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#114+

In [11]:
def f(*args):
    result = []
    for x in args[0]:
        for w in args[1:]:
            if x in w:
                break
        else:
            result.append(x)
    return "".join(result)

s1, s2, s3= "hello", "hi", "good morning"
print(f(s1, s2, s3))

ell


In [ ]:
hellohigoodmorning
hello
goodmorning
hi
ell  #
heloigd mrn
пустая строка

Функция f проходит по каждому символу в первой переданной строке и добавляет его в результат только в том случае, если он не встречается в остальных строках. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
след зад 5 мая 2021

In [ ]:
/////////////////////////////

In [ ]:
#115+

In [1]:
sorted([1, 2, 3, 4, 5], key=lambda x: -x, reverse=True)

[1, 2, 3, 4, 5]

In [ ]:
[1, 2, 3, 4, 5]   #
[-1, -2, -3, -4, -5]
[5, 4, 3, 2, 1]
[-5, -4, -3, -2, -1]
None
TypeError

Код сортирует список в обратном порядке, используя key=lambda x: -x, что инвертирует знаки элементов. Затем, с помощью reverse=True, список снова инвертируется в исходный порядок. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#116+

In [2]:
def f(arr):
    if not arr:
        return 0
    return arr[0] + f(arr[1:]) 
f([1, 2, 3, 4, 5])

15

In [ ]:
0
1
3
5
15    #
IndexError

f рекурсивно суммирует элементы списка arr. Если список пуст, f возвращает 0. Иначе вызывается опять функция f с укороченным на первый элемент списком и прибавляется к первому элементу этого списка.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#117+

In [ ]:
Как называется результат вычисления данной функции?

In [ ]:
def f(n):
    return n * f(n-1) if n > 1 else 1

In [ ]:
факториал  #
свертка
разложение
среднее
подстановка
композиция


Факториал числа - это произведение всех целых чисел от 1 до этого числа включительно. Функция возвращает 1, если n меньше или равно 1; в противном случае возвращает произведение n на факториал n-1.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#118+

In [3]:
def f(arr):
    return 0 if not arr else arr[0] + f(arr[1:])
print(f([]))

0


In [ ]:
0   #
None
IndexError
ValueError
TypeError

Функция f рекурсивно суммирует элементы списка arr. Если список пуст, функция возвращает 0. Вызов f([]) возвращает 0, так как список пуст.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#119 11 январь  2024+

In [4]:
def f(arr):
    return 0 if not arr else arr[0] + f(arr[1:])
print(f([1, 2]))

3


In [ ]:
0
1
2
3  #
4
None
IndexError
ValueError
TypeError

Функция f рекурсивно суммирует элементы списка arr. На каждой итерации возвращает сумму первого элемента списка и результат вызова f от укороченного списка (без первого элемента).

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#120 20 май 2024+

In [5]:
def f(arr):
    return 0 if not arr else arr[0] + f(arr[2:])
print(f([3, 3, 3]))

6


In [ ]:
3
6   #
9
None
IndexError
ValueError
TypeError

На каждой итерации f рекурсивно суммирует элементы списка arr, пропуская элемент под индексом 1. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#121+

In [6]:
def f(arr):
    return arr[0] if len(arr) == 1 else arr[0] + f(arr[1:])
print(f([]))

IndexError: list index out of range

In [ ]:
0
None
IndexError   #
ValueError
TypeError

f рекурсивно суммирует элементы списка arr. Если список состоит из одного элемента, функция возвращает этот элемент. Однако вызов f([]) вызовет ошибку, так как список пуст и arr[0] не определено.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#122+

In [7]:
def f(arr):
    first, *rest = arr
    return first if not rest else first + f(rest)
print(f([]))

ValueError: not enough values to unpack (expected at least 1, got 0)

In [ ]:
0
None
IndexError   
ValueError   #
TypeError

f рекурсивно суммирует элементы списка arr, распаковывая первый элемент и оставшиеся элементы на каждом шаге. Если в rest нет элементов, функция возвращает первый элемент. Однако вызов f([]) вызовет ошибку, так как список пуст и first не определено.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#123+

In [8]:
def f(n):
    def g(x):
        return x**n
    return g
g = f(2)
print(g(7))

49


In [ ]:
0
1
2
4
7
49    #
128
None
TypeError

f принимает число n и возвращает g, которая возводит свой аргумент x в степень n. После вызова f(2), мы получаем g, возводящую число в квадрат. При вызове g(7) получаем результат 49.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#124+

In [9]:
def f():
    _x = None
    def g(x=None):
        nonlocal _x
        if x is None:
            return _x
        _x = x
    return g
g = f()
print(g(), g(10), g(), g(5), g())

None None 10 None 5


In [ ]:
None None 10 10 5
None 10 10 5 5
None None 10 None 5   #
None None 10 5 5
None 10 None 5 None

При установке значений g(10) и g(5) они сохраняются, но возвращается None. При вызове g() возвращается последнее сохраненное значение или None в начале(если не было сохранения).

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
17 may 2021 next task

In [ ]:
/////////////////////

In [ ]:
#125+

In [1]:
def f(x):
    y = x ** 2
    return y
print(*f.__code__.co_varnames)

x y


In [ ]:
x
x 2
x y   #
x y 2
y 2
y

Способ получения локальных переменных функции через объект ее кода

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#126+

In [2]:
def f(x, y):
    f.y = y
    f.z = f.y
    return x
print(f(1, 2), [x for x in dir(f) if not x.startswith('__')])

1 ['y', 'z']


In [ ]:
1 2
1 []
1 [2]
1 ['y', 'z']   #
1 ['x', 'y', 'z']
1 ['x', 'y']
1 ['x', 'z']
NameError
AttributeError

f возвращает первый аргумент, а также устанавливает атрибуты y и z, имена которых выводятся в списковом включении

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#127+

In [4]:
def f(arr):
    return 0 if not arr else arr[0] + f(arr[1:])
print(f(('a', 'b', 'c', 'd')))

TypeError: can only concatenate str (not "int") to str

In [ ]:
abcd
None
TypeError #
IndexError
ValueError

В данной функции f, базовый случай возвращает 0 (число), а затем пытается прибавить к этому результату строку, что вызовет TypeError. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#128+

In [5]:
def f(arr):
    return arr[0] if len(arr) == 1 else arr[0] + f(arr[1:])
print(f(('a', 'b', 'c', 'd')))

abcd


In [ ]:
abcd   #
None
TypeError 
IndexError
ValueError

Если длина массива = 1, функция возвращает первый (и единственный) элемент массива. Если больше 1, функция возвращает результат конкатенации первого элемента массива и результата вызова самой себя с оставшейся частью массива. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#129+

In [6]:
def f(arr):
    first, *rest = arr
    return first if not rest else first + f(rest)
print(f(('H', 'e', 'l', 'l', 'o')))

Hello


In [ ]:
Hello  #
None
TypeError
IndexError
ValueError

f в этом коде рекурсивно объединяет все символы в кортеже, используя распаковку списка для получения первого элемента и оставшейся части. f последовательно соединит все элементы кортежа в одну строку.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#130+

In [7]:
def f(a: int, b: float) -> int:
         return a * int(b) 
print(f(5, 2.1))

10


In [ ]:
7.1
10    #
10.5
TypeError
SyntaxError

Функция f умножает целочисленный аргумент a на целую часть вещественного аргумента b. Анотации типов ни на что не влияют.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#131+

In [8]:
def func(a: str, b: int):
    return a + b 
func(1, 2)
for arg in sorted(func.__annotations__):
    print(arg, func.__annotations__[arg])
    break

a <class 'str'>


In [9]:
func.__annotations__

{'a': str, 'b': int}

In [ ]:
3
a 1
b 2
a 1 b 2
a<class 'str'>   #
b<class 'int'>

Аннотация типов ни на что не влияет - поэтому можно передать func два числа, вместо строки. Словарь аннотации имеет ключ - имя переменной, значение - тип.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#132+

In [10]:
def f(x, y):
    z = x ** y
    return z
print(f.__code__.co_argcount)

2


In [ ]:
0
1
2  #
3
None
AttributeError

co_argcount — общее количество позиционных аргументов (включая только позиционные аргументы и аргументы со значениями по умолчанию);

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#133+

In [11]:
def f(arr):
    s = 0
    for x in arr:
        if not isinstance(x, list):
            s += x
        else:
            s += f(x)
    return s
print(f([1, [2, [3, [4, [5]]]]]))

15


In [ ]:
0
1
15 #
120
None
TypeError

Функция f рекурсивно обходит и суммирует все числа во вложенном списке.

In [ ]:
#134+

In [12]:
from collections.abc import Iterable
def f(arr):
    s = 0
    items = list(arr)
    while items:
        first = items.pop(0)
        if not isinstance(first, Iterable):
            s += first
        else:
            items.extend(first)
    return s
print(f((1, (2, (3, (4, (5)))))))

15


In [ ]:
0
1
15  #
12345
None
TypeError

Функция f итеративно обходит и суммирует все числа во вложенной структуре, используя стек. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#135

In [13]:
def f(L):
    s = ''
    items = list(L)
    while items:
        first = items.pop(0)
        if isinstance(first, str):
            s += first
        else:
            items[:0] = first       
    return s
print(f(('a', ('b', ('c', ('d', 'e'))))))

abcde


In [ ]:
edcba
abcde   #
('e'),('d'),('c'),('b'),('a')
('a'),('b'),('c'),('d'),('e')
'e','d','c','b','a'
'a','b','c','d','e'
de
abc
TypeError

Функция f итеративно обходит и объединяет все строки во вложенной структуре, используя список как стек. 

In [ ]:
............................

In [ ]:
1 june 2021

In [ ]:
#136+

In [ ]:
Какой метод позволяет изменить максимальную глубину рекурсии?

In [ ]:
os.new_recursion
sys.setrecursionlimit   #
platform.recursion
ctypes.set_recursion
sys.recursionlimit
os.recursionlimit
itertools.setlimitrecursion

In [ ]:
https://rollbar.com/blog/python-recursionerror/

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#137+

In [1]:
def f(a: int = 2, b: int = 2) -> int:
    return a ** b
print(f(3))

9


In [ ]:
4
6
9  #
27
TypeError
SyntaxError

В вызове функции f(3), значение a задается как 3, а b остается равным 2, так как его значение не было указано. f возвращает 3 ** 2, что равно 9.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#138+

Какое выражение будет эквивалентным для тернарного оператора 
"b if a else с", считая, что переменные b и c содержат некоторые объекты, а переменная a - булево значение.

In [ ]:
a or b and c
a and b and c
a or b or c
a or c and b
a and b or c    #
a and c or b

In [ ]:
https://book.pythontips.com/en/latest/ternary_operators.html

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [2]:
#139+

In [3]:
f = (lambda х, у: х if х < у else у)
z1 = f('b', 'а')
z2 = f('а', 'b')
print(z1 == z2)

True


In [ ]:
a
b
True   #
False
TypeError

Строки сравниваются лексикографически, поэтому "a" меньше "b". Лямбда-функция f возвращает "a" в обоих случаях, поэтому z1 и z2 равны, и z1 == z2 возвращает True.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#140+

In [4]:
def f(a: int = 5, b: int = 3, c: int = 4) -> int:
    return a + b + c
print(f(2.5, b=2))

8.5


In [ ]:
int
4.5
8.5   #
11
12
TypeError
SyntaxError

f получает a как 2.5, b как 2, а c по умолчанию равно 4. Поэтому f(2.5, b=2) возвращает 2.5 + 2 + 4, что равно 8.5.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#141+

In [5]:
import sys
f = lambda x: list(map(sys.stdout.write, x)) 
t = f(['1', '2', '3'])

123

In [ ]:
[123]
[321]
123   #
1 2 3
321
3 2 1

f - это лямбда-функция, которая использует map для применения sys.stdout.write к каждому элементу списка x, в результате чего каждый элемент выводится на экран без пробелов или новых строк.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#142+

In [6]:
def f(a: int = '1', b: int = '2', c: int = '3') -> int:
    return a + b + c
print(f())

123


In [ ]:
int
str
6
123    #
TypeError
SyntaxError

Функция f с неправильной аннотацией типов(которая ни на что не влияет) возвращает конкатенацию строк '1', '2' и '3'. Таким образом, print(f()) выводит '123' на экран.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#143+

In [7]:
((lambda x: (lambda y:  x ** y)) (3)) (2)

9

In [ ]:
5
6
8
9   #
SyntaxError

Код создаёт лямбда-функцию, которая возвращает другую лямбда-функцию, вычисляющую степень числа x. При подстановке 3 и 2 внешняя и внутренняя функции, соответственно, вычисляются как 3 ** 2, возвращая 9.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#144+

In [8]:
def f(a: 1 = 2) -> 3:
    return 4
print(f())

4


In [ ]:
1
2
3
4  #
TypeError
SyntaxError

В этом коде f() возвращает число 4, поскольку в теле функции указано return 4. Но аннотации типов a: 1 = 2 и -> 3 являются некорректными, так как вместо описания типов там используются числа.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#145+

In [9]:
def f(a: int = float) -> bool:
    return str
print(f())

<class 'str'>


In [ ]:
<class 'int'>
<class'float'>
<class'bool'>
<class'str'>   #
TypeError
SyntaxError

Код выводит <class 'str'>, так как функция f возвращает объект str. Но аннотация типа a: int = float некорректна, поскольку значение по умолчанию float не соответствует ожидаемому типу int.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
...................

In [ ]:
#146+

In [1]:
f = lambda x: print(*x, sep=' ' , end=' ')
t = f(['a', 'b', 'c'])

a b c 

In [ ]:
c b a
cba
a b c   #
abc
a\nb\nc\n
['a', 'b', 'c']
TypeError
SyntaxError

f принимает список в качестве аргумента и использует функцию print для вывода элементов этого списка через пробел без перевода строки на конце. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#147+

In [2]:
def f(a: int = 7) -> int:
    return 2 + int(a)
print(f(3.5))

5


In [ ]:
3.5
5     #
5.5
9
TypeError
SyntaxErrror

f принимает в качестве аргумента значение 3.5, которое сначала приводится к типу int (получаем 3), далее добавляется 2, что в сумме дает 5. Аннотация не влияет.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#148+

In [3]:
list(map(pow, [1, 2, 3], [2, 3, 4]))

[1, 8, 81]

In [ ]:
[1, 4, 9]
[3, 5, 7]
[2, 6, 12]
[1, 8, 81]  #
([1, 8, 9], [4, 9, 16])
SyntaxError

Функция pow применяется к каждой паре значений из этих списков. То есть вычисляются следующие значения: pow(1, 2), pow(2, 3), и pow(3, 4)

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#149+

In [4]:
def f(x: 1 = 1):
    f.__annotations__["x"] += x
    return f.__annotations__["x"]
print(f(), f(), f(10))

2 3 13


In [ ]:
1 1 10
2 3 4
2 3 13   #
TypeError
SyntaxError
KeyError

f.__annotations__ хранит аннотации функции. В каждом вызове f, аннотация "x" увеличивается на x (по умолчанию 1, в последнем вызове 10). 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#150+

In [6]:
def f(x: int = 1):
    if type(x) is not f.__annotations__["x"]:
        raise TypeError("Неправильный тип аргумента x!")
    f.__annotations__["x"] = float
    return x**2

In [ ]:
Какая строка не приведет к возникновению ошибки?

In [ ]:
print(f(1.0))
print(f(), f())
print(f(), f(2))
print(f(1), f(2))
print(f(1), f(2.0))   #
print(f(1.0), f(2.0))

Функция проверяет, соответствует ли тип аргумента x его аннотации. Сперва это int, но после первого прохождения аннотация x меняется на float, что требует далее тип float.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#151+

In [7]:
def f(x): 
    return x + 2 
list(map(f, [1, 2, 3, 4])) == [f(x) for x in [1, 2, 3, 4]]

True

In [ ]:
True  #
False
TypeError
SyntaxError

Два способа применения функции f к заданном списку дают одинаковый результат.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#152+

In [ ]:
Даны 4 варианта кода:

In [ ]:
# 1 вариант
list(filter((lambda x: x > 0) , range(-5, 5)))
# 2 вариант
res = []
for x in range(-5, 5):
    if x > 0:
        res.append(x)
print(res)
# 3 вариант
[х for х in range(-5, 5) if х > 0] 
# 4 вариант
list(map(lambda x: x > 0, range(-10, 5)))

In [20]:
Какой  вариант не  выведет [1, 2, 3, 4]

[1, 2, 3, 4]

In [ ]:
1 вариант
2 вариант
3 вариант
4 вариант #

In [ ]:
В последнем варианте числа преобразуются в булевские значения.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#153+

Какую функцию функционального программирования реализует данная функция?

In [13]:
def f(function, sequence):
    s = sequence[0]
    for x in sequence[1:]:
        s = function(s, x)
    return s

In [ ]:
map
filter
reduce  #
lambda

В цикле переменная s каждый раз заменяется на новую, которая есть применение к s переданной функции и одного из аргументов последовательности, что соответствует определению свертки.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#154+

In [14]:
import operator, functools
x1 = functools.reduce(operator.add, [2, 4, 6])
x2 = functools.reduce((lambda x, у: x + у) , [2, 4, 6])
print(x1 == x2)

True


In [ ]:
True  #
False
SyntaxError

Оба вызова functools.reduce применяют сложение к элементам списка [2, 4, 6], получая в итоге 12.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#155+

In [18]:
from functools import reduce
def f(acc, x):
    acc[x] = x * 2
    return acc
reduce(f, ["a", 3, (1,2)], {})

{'a': 'aa', 3: 6, (1, 2): (1, 2, 1, 2)}

In [ ]:
['aa', 6, (2, 4)]
{'aa', 6, (2, 4)}
['aa', 6, (1, 2, 1, 2)]
{'aa', 6, (1, 2, 1, 2)}
['a':'aa',  3:6, (1, 2):(1, 2, 1, 2)]
{'a': 'aa', 3: 6, (1, 2): (1, 2, 1, 2)} #

Последовательно применяется f к элементам списка ["a", 3, (1,2)]. Начальное значение аккумулятора - пустой словарь. Функция f для каждого элемента x добавляет в словарь acc пару ключ-значение, где ключ — это x, а значение — это x * 2.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#156+

In [19]:
password = 'password'
adding = [х + у for х in '0123456789' for у in '0123456789']
count = 0
for a in adding:
    password = password + a
    count += 1
print(count, password[-3:])

100 899


In [ ]:
100 d99
100 889
100 899   #
200 d99
200 889
200 899
1024 d99
1024 889
1024 899

count равен len(adding) - а это все пары цифр от 0 до 9, то есть 10*10 = 100. В конце password будет содержать последний элемент adding (99) и одну(последнюю) цифру из 98 - 8.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
30  june 2021

In [ ]:
//////////////////////////////

In [ ]:
#157+

In [1]:
from functools import partial
from operator import gt
gt = partial(gt, 0)
l = list(filter(gt, [x for x in range(-2, 3) if x >= 0]))
print(l)

[]


In [ ]:
[]                  #
[-2, -1]
[1, 2]
[-2, -1, 0]
[0, 1, 2]
[-2, -1, 1, 2]
[0]

gt(a, b) <=> a > b; gt = partial(gt, 0) => gt(x) <=> 0 > x 
Создается списковое выражение с неотрицательными числами, затем фильтруем только на отрицательные, в итоге - ничего нет.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#158+

In [1]:
from functools import partial
from operator import lt
gt = partial(lt, 0)
l = list(filter(gt, [x for x in range(-2, 3) if x <= 0]))
print(l)

[]


In [ ]:
[]                  #
[-2, -1]
[1, 2]
[-2, -1, 0]
[0, 1, 2]
[-2, -1, 1, 2]
[0]

lt(a, b) <=> a < b; lt = partial(lt, 0) => lt(x) <=> 0 < x 
Создается списковое выражение с неположительными числами, затем фильтруем только на положительные, в итоге - ничего нет.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#159+

In [8]:
M = [[1, 2], [3, 4]]
N = [[5, 6], [7, 8]]
sum([col1*col2 for row1, row2 in zip(M, N) for col1, col2 in zip(row1, row2)])

70

In [ ]:
36
62
70  #
94
100
5760

Поэлементное умножение двух матриц M и N и суммирует результаты. Используя zip дважды для итерации по строкам и столбцам обеих матриц, мы получаем общую сумму 1*5 + 2*6 + 3*7 + 4*8 = 70

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#160+

In [ ]:
Какую из функций нужно явно импортировать, чтобы ее использовать?

In [ ]:
map
filter
reduce   #
vars
classmethod
dir
repr

In [ ]:
В современном Python функция reduce находится в модуле functools

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#161+

In [ ]:
Даны 4 варианта кода:

In [ ]:
#1
[х ** 2 for х in range(5) if х % 2 == 0]
#2
list(map(lambda x: x**2, filter(lambda x: x % 2 == 0, range(5))))
#3
res = []
for x in range(5):
    if x % 2 == 0:
        y = x**2
        res.append(y)
print(res)
#4
list(map(lambda x: x ** 2 % 4 == 0, range(5)))

In [ ]:
Какой из вариантов не выведет [0, 4, 16]?

In [ ]:
1
2
3
4  #

In [ ]:
Вариант 4 выводит булевский массив, а не числа

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#162+

In [14]:
[(х, у) for х in range(3) if х % 2 == 0 for у in range(3) if у % 2 == 1]

[(0, 1), (2, 1)]

In [ ]:
[(0,1)]
[(2,1)]
[(0,1),(2,1)]    #
[(0,1),(0,2),(2,1)]
[(0,1),(0,3),(2,1),(2,3)]

Этот код генерирует список кортежей (x, y), где x - это числа из диапазона от 0 до 2, удовлетворяющие условию "x четное", а y - это числа из того же диапазона, но удовлетворяющие условию "y нечетное".

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#163+

In [15]:
res = [х ** у for х in [2, 3] for у in [2, 3]]
print(res)

[4, 8, 9, 27]


In [ ]:
[4,8]
[4,27]
[8,9]
[9,27]
[2,3,2,3]
[4,6,6,9]
[4,8,9,27]  #

[2, 3] возводится в [2, 3] поэлементно каждый с каждым. Получаем 4, 8, 9, 27, что это соответствует 2^2, 2^3, 3^2, 3^3.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#164+

In [21]:
listoftuple = [(0, 1, 2), (1, 2, 3)]
s1 = [b  for (a, b, c) in listoftuple]
print(s1)
s2 = list(map(lambda row: row[1], listoftuple))
print(s1 == s2, sum(s1))

[1, 2]
True 3


In [ ]:
True 1
False 1
True 2
False 2
True 3   #
False 3
True 6 
False 6
SyntaxError

Код создает два списка s1 и s2, извлекая второй элемент из каждого кортежа в listoftuple. В первом случае это делается с помощью генератора списков, во втором - с помощью функции map и лямбда-функции. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#165+

In [22]:
def gen():
    for i in range(1, 5):   
        x = yield i
        if x:
            yield x**2
g = gen()
v = g.send(g.send(next(g) + next(g)) + next(g))
print(v)

144


In [ ]:
1
3
4
9
16
81
121
144     #
StopIteration
None

In [ ]:
next(g) генерирует числа подряд 1, 2, 3 и тд. 
g.send(next(g) + next(g))=g.send(1 + 2)=3^2=9
g.send(9+next(g))=g.send(9+3)=12^2=144

In [ ]:
12 июля 2021

In [ ]:
..............................

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#166+

In [ ]:
Какое использование генераторного выражения будет некорректным?

In [ ]:
#1
sorted(x ** 2 for x in range(4))

#2
sorted((x ** 2 for x in range(4)))

#3
sorted((x ** 2 for x in range(4)), reverse=True)

#4
sorted(x ** 2 for x in range(4), reverse=True)   

#5
list(x ** 2 for x in range(4))

In [ ]:
1
2
3
4  #
5


Если в sorted есть второй аргумент, то генераторное выражение надо брать в скобки

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#167+

In [2]:
import math
sum(map(math.sqrt, (x ** 2 for x in range(3))))

3.0

In [ ]:
0.0
1.0
3.0   #
5.0
6.0
14.0


Код вычислит сумму квадратных корней чисел, полученных путем возведения в квадрат чисел от 0 до 2.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#168 май 2024+

In [5]:
g1 = (c * 2 for c in 'ABC')
def gen(m): 
    for c in m:
        yield c * 2
g2 = gen('ABC')
print(list(g1) == list(g2))

True


In [ ]:
True   #
False
TypeError
SyntaxError

Два способа задания генератора приводят к одному результату - списку AA, BB, CC.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#169+

In [10]:
G = (с for с in '123')  
I1 = iter(G)  
I2 = iter(G)
_ = next(I1)
_ = next(I1)
print(next(I2))

3


In [ ]:
1
2
3   #
123
123 123
123 123 123
None
StopIteration

Итераторы I1 и I2 связаны с одним общим генератором, откуда берутся значения. Поэтому дважды вызов next(I1) возвращает 1 и 2, а next(I2) - вернет уже 3.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#170+

In [11]:
def f(n):
    yield from range(n)
    yield from (x ** 2 for x in range(n))
res = ':'.join(str(i) for i in f(3))
print(res)

0:1:2:0:1:4


In [ ]:
0:1:2
0:1:4
0:1:2:0:1:4   #
0:1:2:0:1:2
0:1:4:0:1:4

Конструкция yield from делегирует вызовы другому генератору, пока он не исчерпан. Генератор f возвращает значения из двух других генераторов.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#171+

In [20]:
line = 'aaa bbb ccc d e f'
g1 = ''.join(x.upper() for x in line.split() if len(x) > 1)
def gen(line): 
    for x in line.split():
        if len (x) > 1:
            yield x.upper()
g2 = ''.join(gen(line))
print(g1 == g2)

True


In [ ]:
True   #
False
TypeError
SyntaxError

Два способа задания генератора приводят к одному результату. Отфильтровываем слова с длиной больше 1 и преобразуем к верхнему регистру. Затем склеиваем.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#172+

In [21]:
def gen(n):
    for i in n:
        yield i
g = gen('abcd')
l = len(list(g))
print(next(g), l)

StopIteration: 

In [ ]:
'a' 4
'' 4
'a' 0
'' 0
'' 0
'abcd' 0
'abcd' 4
StopIteration   #
TypeError

Вызов list(g) исчерпывает генератор, поэтому последующий next(g) приводит к исключению StopIteration.

In [ ]:
21 july 2021

In [ ]:
//////////////

In [ ]:
#173+

In [1]:
def f(a, b, c):
    return (a + 2*b) ** c
w = {"a": 1, "b": 2, "c": 3}
print(f(**w))

125


In [ ]:
0
(a+2*b)**c
64
125  #

Код использует словарь w в качестве именнованных аргументов для функции f(a, b, c), которая вычисляет выражение (a + 2*b) ** c.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#174+

In [2]:
ranks = {'aaa': 1, 'bbbb': 2}
rank_dict = {rank: name for name, rank in ranks.items()}
set_len = {len(name) for name in rank_dict.values()}
print(rank_dict, set_len)

{1: 'aaa', 2: 'bbbb'} {3, 4}


In [ ]:
{'aaa':1, 'bbbb':2}{1, 2}
{'aaa':1, 'bbbb':2}{3, 4}
{'aaa':1, 'bbbb':2}{1, 2, 3, 4}
{1: 'aaa', 2: 'bbbb'} {1, 2}
{1: 'aaa', 2: 'bbbb'} {3, 4}  #
{1: 'aaa', 2: 'bbbb'}{1, 2, 3, 4}

Код обращает пары ключ-значение в словаре ranks, формируя новый словарь rank_dict. Затем он создает множество set_len, включающее длины всех строк-значений в rank_dict. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#175

In [3]:
def f(seq):
    if not seq:  
        return [seq]
    else:
        res = []
        for i in range(len(seq)):
            rest = seq[:i] + seq[i+1:] 
            for x in f(rest):
                res.append(seq[i:i+1] + x)
        return res
a = f([1, 2])
b = f([1, 2, 3, 4, 5])
print(a, len(b))

[[1, 2], [2, 1]] 120


In [ ]:
[2,1]120
[1,2]120
[[1,2],[2,1]]120   #
[2,1]15
[1,2]15
[[1,2],[2,1]]15
[2,1]5
[1,2]5
[[1,2],[2,1]]5

Функция f создает все перестановки принятой последовательности элементов. Количество перестановок из n элементов определяется как n!.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
26 july 2021

In [ ]:
......................

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#176+

In [1]:
x = [[0] for i in range(3)]
x[0].append(1)
print(x)

[[0, 1], [0], [0]]


In [ ]:
[[0, 1], [0], [0]]  #
[[0, 1], [0]]
[[0, 1], [0, 1]]
[[0, 1], [0, 1], [0, 1]]
[[0, 1], [1], [1]]
[[1], [1], [1]]
[[1]]
TypeError
IndexError

Здесь 1 добавится только в первый внутренний список [0], так как генератор списка создает каждый раз новый

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#177+

In [8]:
def f(*seqs):
    seqs = [list(S) for S in seqs]
    res = []
    while all(seqs):
        res.append(tuple(S.pop(0) for S in seqs))
    return res
s1, s2 = 'abc', '12345'
print(list(zip(s1, s2)) == f(s1, s2))

True


In [ ]:
True   #
False
TypeError
SyntaxError

Код сравнивает результаты функций zip и f, оба из которых объединяют элементы переданных строк в кортежи. f - это реализация zip

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#178+

In [10]:
def f(*seqs, pad=None):
    seqs = [list(S) for S in seqs]
    res = []
    while any(seqs):
        res.append(tuple((S.pop(0) if S else pad) for S in seqs))
    return res

s1, s2 = 'abc', '12345'
print(list(zip(s1, s2)) == f(s1, s2))

False


In [11]:
f(s1, s2)

[('a', '1'), ('b', '2'), ('c', '3'), (None, '4'), (None, '5')]

In [ ]:
True
False   #
TypeError
SyntaxError

f соединяет элементы переданных строк в кортежи даже после исчерпания самой короткой строки, заполняя "пустые" места значением None. Выводом будет False, так как zip(s1, s2) отбрасывает с None

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#179+

In [2]:
def f(*seqs):
    minlen = min(len(s) for s in seqs)
    return [tuple(s[i] for s in seqs) for i in range(minlen)]

s1, s2 = 'ab' , 'xyz'
print(f(s1, s2))

[('a', 'x'), ('b', 'y')]


In [ ]:
[('a','x'), ('b', 'y')]   #
[('a','x'), ('b', 'y'), (None, 'z')]
[('a', 'b'), ('x', 'y')]
[('a', 'b', None), ('x', 'y', 'z')]

f в этом коде создает список кортежей, соединяя соответствующие элементы переданных последовательностей. Для s1 = 'ab' и s2 = 'xyz', результатом будет [('a', 'x'), ('b', 'y')].

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#180+

In [12]:
def f(seq):
    if not seq:
        yield seq
    else:
        for i in range(len(seq)):
            rest = seq[:i] + seq[i+1:]
            for x in f(rest):
                yield seq[i:i+1] + x
a = [*f(['a', 'b'])]
b = [*f(['a', 'b', 'c', 'd'])]
print(a, len(b))

[['a', 'b'], ['b', 'a']] 24


In [5]:
['a', 'b'] 24
['b', 'a'] 24
[['a', 'b'], ['b', 'a']] 24  #
['a', 'b'] 6
['b','a'] 6
[['a', 'b'], ['b', 'a']] 6
['a', 'b'] 4
['b', 'a'] 4
[['a', 'b'], ['b', 'a']] 4

SyntaxError: invalid syntax (<ipython-input-5-c639f1399d5f>, line 1)

f создает все возможные перестановки элементов списка. Переменная a будет содержать все перестановки из a, b.  len(b) равно числу всех возможных перестановок из 4 элементов, т е 4! = 24.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#181+

In [6]:
_ = [i for i in range(10)]
print(i)

NameError: name 'i' is not defined

In [ ]:
0
1
9
10
NameError  #
TypeError

Переменная i определена только внутри области видимости генератора списка 

In [ ]:
2 авг 2021

In [ ]:
/////////////////////////

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#182+

In [1]:
def f(seq):
    for i in range(len(seq)):
        yield seq[i:] + seq[:i]
print((list(f('123'))))

['123', '231', '312']


In [ ]:
['123', '231', '312']    #
['231', '312', '123']
['312', '123', '231'] 
['312', '231', '123'] 

Генератор последовательно возвращает циклические сдвиги заданной строки, проходя через все символы строки seq и на каждом шаге сдвигая строку на одну позицию влево, добавляя отброшенный символ в конец

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#183+

In [2]:
{x + y: (x, y) for x in 'ab' for y in 'c' if not x.startswith('a')}

{'bc': ('b', 'c')}

In [ ]:
{'ac': ('a', 'c')}
{'bc': ('b', 'c')}  #
{'ab': ('a', 'b')}
{'ac': ('a', 'c'), 'bc': ('b', 'c')}

Код создает словарь, где ключами являются конкатенации строк из переменных x и y, а значениями - кортежи из x и y. Отбрасываются те x, что начинаются на 'a'.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#184+

In [8]:
try:
    assert False, "assert"
    print("try")
except Exception as err:
    print(err)
else:
    print("else")

assert


In [ ]:
try
assert   #
except
else
None

Строка с assert генерирует исключение, так как туда передано False (assert требует истинности условия), второй аргумент - текст ошибки, что будет выведен в секции except

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#185+

In [9]:
def f(*seqs, pad=None):
    maxlen = max(len(S) for S in seqs)
    index = range(maxlen)
    return [tuple((S[i] if len(S) > i else pad) for S in seqs) for i in index]
s1, s2 = 'ab' , 'xyz'
print(f(s1, s2))

[('a', 'x'), ('b', 'y'), (None, 'z')]


In [ ]:
[('a', 'x'), ('b', 'y')]
[('a', 'x'), ('b', 'y'), (None, 'z')]  #
[('a','b'), ('x', 'y')]
[('a','b', None), ('x', 'y', 'z')]

Этот код выравнивает несколько последовательностей (строк) до длины самой длинной из них, заполняя недостающие элементы символом pad. Здесь используется значение pad по умолчанию, то есть None. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#186+

In [10]:
def mymap(func, *seqs):
    res = []
    for args in zip( *seqs):
        res.append(func( *args))
    return res
x = [1, 2, 3]
y = [2, 3, 4, 5]
a = mymap(pow, x, y)
b = [*map(pow, x, y)]
print(a == b)

True


In [ ]:
True  #
False
None
TypeError
SyntaxError

Функции mymap и map применяют функцию возведения в степень (pow) к парам элементов из списков x и y. Код выведет True, так как обе функции возвращают одинаковые списки [1, 8, 81], не учитывая "лишний" элемент в списке y.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#187+

In [11]:
def f(seq):
    for i in range(len(seq)):
        seq = seq[1:] + seq[:1]
        yield seq
print(''.join(list(f('xy'))))

yxxy


In [ ]:
xxyy
yyxx
xyyx
yxxy   #
yxyx

Этот код создаёт генератор, который выполняет циклический сдвиг символов строки влево на каждом шаге. В результате из xy получаются yx и снова xy.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#188+

In [12]:
class MyExc(Exception): pass 
def f():
    raise MyExc()
    return  'f'
try:
    print(f())
    print('try')
except MyExc:
    print('exc')

exc


In [ ]:
f
try
exc  #
None

Код определяет исключение MyExc, затем вызывает функцию f(), которая немедленно вызывает это исключение. Таким образом, f() не завершается нормально и не возвращает 'f'. Следовательно, код выведет 'exc', так как исключение MyExc было обработано в блоке except.

Функция f вызывает исключение MyExc, поэтому код выведет 'exc', так как исключение MyExc было обработано в блоке except.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
10 авг 2021

In [ ]:
.......................................

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#189+

In [ ]:
Какой случай не относится к вариантам применения исключения?

In [ ]:
обработка ошибок
выполнение действий при завершении
уведомления о событиях
безусловный переход
оптимизация медленных вычислений  #

In [ ]:
Оптимизация медленных вычислений и обработка исключений никак не связаны.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#190+

In [1]:
x = 0
try:
    1/0
    x += 1
except ZeroDivisionError:
    x += 1
else: 
    x += 1
    1/0
    x += 1
print(x)

1


In [ ]:
0
1  #
2
3
4
ZeroDivisionError

Этот код приведет к исключению ZeroDivisionError при попытке деления на ноль в блоке try. В результате переменная x, инициализированная как 0, увеличивается на 1 в блоке except, в результате чего в конце будет напечатано значение 1.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#191+

In [5]:
try:
    print('try')
    1/0
else:
    print('else')

SyntaxError: invalid syntax (<ipython-input-5-44443bbeb57e>, line 4)

In [ ]:
try
else
SyntaxError  #
ZeroDivisionError

Блок else должен следовать за блоками except, и если его нет, то будет вызвана ошибка синтаксиса SyntaxError.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#192+

In [6]:
x = 0
try:
    x += 1
except ZeroDivisionError:
    x += 1
else: 
    x += 1
    1/0
    x += 1
print(x)

ZeroDivisionError: division by zero

In [ ]:
0
1
2
3
4
ZeroDivisionError  #

Деление на 0 происходит в блоке else, а не try, поэтому оно не будет обработано

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#193+

In [7]:
d = {'a': 1, 'b': 2, 'c': 3}
x = [string for string, digit in d.items() if digit > 1]
print(x)

['b', 'c']


In [ ]:
[1, 2, 3]
[2, 3]
['c']
['b', 'c']      #
['a', 'b', 'c']

Код создает список, который содержит ключи словаря d, для которых соответствующие значения больше 1. В данном случае это 'b' и 'c'. Поэтому на выходе мы получим список ['b', 'c'].






In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#194+

In [8]:
sum([1 << i for i in range(5)])

31

In [ ]:
0
7
16
31  #
32
43
63

Код вычисляет сумму последовательности, где каждое значение является результатом операции сдвига влево числа 1 на i бит. В итоге, будет выведено число 31, которое является суммой 1, 2, 4, 8, и 16.

In [ ]:
18 августа 2021

In [ ]:
...................

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#195+

In [1]:
x = 0
try:
    x += 1
    try: 
        x += 1
        1/0
    except ZeroDivisionError:
        x += 1
except ZeroDivisionError:
    x += 1
else: 
    x += 1
print(x)

4


In [ ]:
0
1
2
3
4 #
5
ZeroDivisionError

Не выполняется внешний блок except ZeroDivisionError, так как обрабатывается внутри вложенного try-except блока. В остальных случаях x увеличивается каждый раз.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#196+

In [ ]:
Что выведет код?

In [2]:
def f(*seqs):
    seqs = [list(s) for s in seqs]
    while all(seqs):
        yield tuple(s.pop(0) for s in seqs)
s1, s2 = 'ab', '123'
print(list(f(s1, s2)))

[('a', '1'), ('b', '2')]


In [ ]:
[('a', '1')]
[('a', '1'), ('b', '2')] #
[('b', '2'), ('a', '1')]
[('a', '1'), ('b', '2'), (None,3)]
[(None,3), ('b', '2'), ('a', '1')]

Функция берет по одному элементу из строк s1 и s2 одновременно, пока не закончатся элементы в более короткой строке. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#197+

In [3]:
class A:
    def message(self):
        print('1', end='') 
        
    def __enter__(self):
        print('2', end='') 
        return self
    
    def __exit__(self, exc_type, exc_value, exc_tb):
        if exc_type is None:
            print('3', end='')  
        else:
            print ('4', end='')
            return True   
        
with A() as action:
    action.message()


213

In [ ]:
1234
123
2134
213 #
214
23
24

При входе в with вызывается метод __enter__ класса A, выводя 2. Затем - message, выводя 1. После выполнения блока with __exit__ проверяет наличие исключения и, не обнаружив его, выводит 3. 

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#198+

In [4]:
class Error(Exception): pass

def handle(file):
    raise Error()
    
file = open('mydata', 'w') 

try:
    handle(file)
    print('one')
finally:
    file.close() 

print('two')


Error: 

In [5]:
one
two
Error  #
SyntaxError

NameError: name 'one' is not defined

Исключение бросается в функции handle, поэтому строка 'one' не печатается. Блок finally гарантирует, что файл закрывается независимо от исключения.

In [ ]:
#199

In [7]:
sum([3 >> i for i in range(200)])

4

In [ ]:
0
1
2
3
4
5
200
2134
456657

Сдвиг вправо числа 3 на 2 и более позиций даст 0, так как 3 в двоичной системе 11, и сдвиг на две позиции обнулит его. Только первые два элемента списка (3 и 1) не равны 0.

In [ ]:
25 августа 2021

In [ ]:
//////////////////////////////////////

In [ ]:
#200+

In [1]:
val = # ваш код
shoes = {'name': 'fashion shoes', 'price': 14900}
def discount(item, discount):
    price = int(item['price']) * (1.0 - discount)
    assert 0 <= price <= item['price']
    return price
discount(shoes, val)


SyntaxError: invalid syntax (<ipython-input-1-241f1bb44846>, line 1)

In [ ]:
При каком значении val появится ошибка AssertionError?

In [3]:
0.1
0.2
0.9
1
1.2 #

1

# 

Значение 1.2 для val приведет к ошибке, так как результатом будет отрицательная цена, нарушая условие assert. Скидка должна быть в пределах 0 до 1, где 1 соответствует полной скидке на товар.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#201+

In [4]:
class MyExc(Exception):
    def __str__(self): 
        return 'my-exc'
try:
    raise MyExc()
    print('try')
except MyExc as err:
    print(err)
else:
    print('else')


my-exc


In [ ]:
my-exc  #
try
else
None

In [ ]:
Что выведет код. Объясни в 200 знаков

Код выведет "my-exc", так как исключение MyExc вызывается и перехватывается блоком except, где через print выводится результат метода str класса исключения.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#202+

In [5]:
class A:
    def __enter__(self):
        print('1', end='')
        return None
    def __exit__(self, exc_type, exc_value, exc_tb):
        if exc_type is None:
            print('3', end='')  
        else:
            print ('4', end='')
            return True
    
with A() as a:
    print("2" if a else "3", end='')
    raise Exception
    print("5", end="")


134

In [ ]:
124
134 #
1245
1345
1234
12345

Код выведет "134". Сначала "1" из метода __enter__, затем "3" из условия в блоке with, и после возникновения исключения "4" из метода __exit__, где исключение обрабатывается.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#203+

In [6]:
{k.upper() : k * 2 for k in [ 'hello', 'hi', 'good morning' ] if k[0] == 'h'}


{'HELLO': 'hellohello', 'HI': 'hihi'}

In [7]:
{'HELLO', 'HI'}
{'hellohello', 'hihi'}
{'HELLO': 'hellohello', 'HI': 'hihi'} #
{'HELLO': 'hellohello', 'HI': 'hihi', 'GOOD MORNING:'good morninggood morning'}

{'HELLO': 'hellohello', 'HI': 'hihi'}

Код создает словарь с ключами в верхнем регистре для строк, начинающихся на 'h', и значениями в виде удвоенных строк.






In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты

In [ ]:
#204

In [8]:
_  = dict((x, x * x) for x in range(10))
print(x)


NameError: name 'x' is not defined

In [ ]:
0
1
9
10
NameError #
TypeError

Код вызовет ошибку NameError, так как переменная x не определена в области видимости, где происходит вызов print(x). Генератор внутри dict не создает x во внешней области.

In [ ]:
Что выведет код?
```python
```
Что выведет код?
Выберите правильный вариант
Посмотреть результаты